import type { MetricInterpretationContext } from './financialMetricContext';
import { attachBeginnerEducation, beginnerMeaningForContext, type MetricEducation } from './metricBeginnerEducation';

export interface MetricMeaning { name: string; th: string; en: string; education?: MetricEducation }
// Educational metadata only. These definitions never supply values or replace
// formulas, period selection or sector policy in the verified accounting registry.
export const METRIC_MEANING_REGISTRY: Record<string, MetricMeaning> = {};
function define(keys: string, name: string, th: string, en: string) {
  for (const key of keys.split('|')) METRIC_MEANING_REGISTRY[key] = { name, th, en };
}
define('research_and_development_excluding_acquired', 'R&D excluding acquired in-process research',
  'ค่าใช้จ่ายวิจัยและพัฒนาที่ไม่รวมโครงการวิจัยระหว่างดำเนินการที่ซื้อมา เป็นขอบเขตค่าใช้จ่ายเฉพาะตามการเปิดเผย ไม่ใช่ค่า R&D รวมทั้งหมด ใช้ดูทรัพยากรพัฒนาสินค้าเทียบรายได้และกำไรโดยต้องเทียบขอบเขตเดียวกัน',
  'Recognized R&D expense excluding acquired in-process research. This narrower disclosed scope is not total R&D. Compare development effort with revenue and profit using the same expense scope across periods.');
define('selling_and_marketing', 'Selling and Marketing',
  'ค่าใช้จ่ายด้านการขายและการตลาดที่รับรู้ตามบัญชี ใช้เทียบรายได้เพื่อดูประสิทธิภาพการหาลูกค้า แต่ต้นทุนที่เพิ่มอาจสนับสนุนการเติบโต ต้องพิจารณาคุณภาพรายได้และกำไรควบคู่กัน',
  'Recognized selling and marketing costs. Compare with revenue to assess acquisition effort, while recognizing that higher spending may support future growth. Consider revenue quality and profitability together.');
define('general_and_administrative', 'General and Administrative',
  'ค่าใช้จ่ายบริหารและสนับสนุนองค์กรตามบัญชี ไม่รวมค่าใช้จ่ายขายที่แยกเปิดเผย ใช้ดูต้นทุนโครงสร้างเทียบรายได้และขนาดธุรกิจ การลดค่าใช้จ่ายไม่จำเป็นต้องดีหากกระทบการดำเนินงาน',
  'Recognized corporate administrative and support costs, separate from disclosed selling costs. Assess overhead relative to revenue and scale; reductions are not automatically favorable if they weaken operations.');
define('revenue', 'Revenue',
  'รายได้คือยอดขายสินค้าและบริการที่รับรู้ตามบัญชีก่อนหักต้นทุนและค่าใช้จ่าย สะท้อนขนาดธุรกิจและกิจกรรมการขายซึ่งอาจได้รับผลจากปริมาณ ราคา และส่วนผสมสินค้า แต่รายได้อย่างเดียวไม่ยืนยันสาเหตุเหล่านี้ นักลงทุนควรดูคุณภาพการเติบโตควบคู่กับอัตรากำไรและกระแสเงินสด เพราะยอดขายที่เพิ่มไม่ได้แปลว่ากำไรหรือเงินสดเพิ่มตามเสมอไป',
  'Revenue is recognized sales of goods and services before costs and expenses. It reflects business scale and sales activity, which can be influenced by volume, pricing and mix without identifying those drivers by itself. Investors assess growth quality alongside margins and operating cash flow because more sales do not necessarily produce more profit or collected cash.');
define('operating_margin|ebit_margin', 'Operating Margin',
  'อัตรากำไรดำเนินงานคือกำไรจากการดำเนินงานเทียบกับรายได้ หลังหักต้นทุนขายและค่าใช้จ่ายดำเนินงาน สะท้อนประสิทธิภาพที่ธุรกิจหลักเปลี่ยนยอดขายเป็นกำไร โดยยังไม่ใช่กำไรหลังภาษีหรือเงินสดที่เก็บได้ นักลงทุนใช้ดูโครงสร้างต้นทุนและผลของขนาดธุรกิจ ควบคู่กับการเติบโตของรายได้ อัตรากำไรขั้นต้น และค่าใช้จ่ายดำเนินงานก่อนสรุปเรื่องอำนาจกำหนดราคา',
  'Operating Margin is operating income relative to revenue after direct costs and operating expenses. It measures how efficiently the core business converts sales into profit, before financing and tax effects, and is not cash conversion. Investors assess cost structure and operating leverage alongside revenue growth, gross margin and operating expenses rather than inferring pricing power from this ratio alone.');
define('gross_margin', 'Gross Margin',
  'อัตรากำไรขั้นต้นคือกำไรที่เหลือจากรายได้หลังหักต้นทุนขายเทียบกับรายได้ สะท้อนเศรษฐศาสตร์ของสินค้าและบริการก่อนค่าใช้จ่ายดำเนินงาน นักลงทุนใช้ประเมินความสัมพันธ์ระหว่างราคาขายและต้นทุนโดยตรง แต่การเปลี่ยนแปลงอาจมาจากส่วนผสมสินค้าหรือวิธีรับรู้ต้นทุน จึงควรดูรายได้ ต้นทุนขาย และอัตรากำไรดำเนินงานประกอบ',
  'Gross Margin measures gross profit retained from revenue after direct costs, before operating expenses. It reflects product or service economics and the relationship between selling prices and direct costs. Investors compare revenue, cost of sales and operating margin because changes may also reflect sales mix or cost recognition rather than pricing power alone.');
define('net_income|net_income_cont|net_income_parent|net_income_common', 'Net Income',
  'กำไรสุทธิคือผลกำไรทางบัญชีหลังต้นทุนและค่าใช้จ่ายสำคัญ รวมถึงดอกเบี้ยและภาษี โดยขอบเขตการจัดสรรให้ผู้ถือหุ้นต้องตรงกับรายการที่เลือก สะท้อนผลลัพธ์สุดท้ายของการทำกำไรแต่ไม่ใช่เงินสดที่ได้รับทั้งหมด นักลงทุนควรดูรายการที่เกิดครั้งเดียว กำไรดำเนินงาน และกระแสเงินสดเพื่อประเมินความต่อเนื่องและคุณภาพกำไร',
  'Net Income is the accounting profit after major costs, expenses, financing and tax, with shareholder attribution defined by the selected reported line. It reflects bottom-line profitability but is not the same as cash collected. Investors assess recurring earnings quality alongside operating income, one-off items and operating cash flow.');
define('ocf|operating_cash_flow', 'Operating Cash Flow',
  'กระแสเงินสดจากการดำเนินงานคือเงินสดสุทธิจากกิจกรรมดำเนินงานในช่วงเวลาที่เลือก สะท้อนการแปลงผลประกอบการเป็นเงินสดหลังผลของรายการที่ไม่ใช่เงินสดและเงินทุนหมุนเวียน นักลงทุนใช้ประเมินคุณภาพกำไรและความสามารถสนับสนุนกิจการ ควบคู่กับกำไรสุทธิ ลูกหนี้ สินค้าคงเหลือ และรายจ่ายฝ่ายทุน โดยธุรกิจการเงินต้องคำนึงถึงกระแสสินเชื่อและเงินฝากด้วย',
  'Operating Cash Flow is net cash from operating activities over the selected period. It reflects earnings conversion after non-cash adjustments and working-capital movements, helping investors assess earnings quality and funding capacity. Compare net income, receivables, inventory and capital expenditure; lending and deposit flows require additional care for financial institutions.');
define('fcf|free_cash_flow', 'Free Cash Flow',
  'กระแสเงินสดอิสระตามนิยามนี้คือกระแสเงินสดจากการดำเนินงานที่เหลือหลังหักเงินสดจ่ายลงทุนในสินทรัพย์ถาวร ช่วยประเมินเงินสดที่กิจการเหลือหลังการลงทุน แต่ไม่ได้หมายถึงเงินสดที่สามารถแจกจ่ายได้ทั้งหมด นักลงทุนควรดูรายจ่ายฝ่ายทุน ภาระหนี้ และความต่อเนื่องของเงินสดดำเนินงาน โดยไม่นำเกณฑ์นี้ไปใช้ประเมินธนาคารแบบบริษัททั่วไป',
  'Free Cash Flow under this methodology is operating cash flow less the capital expenditure outflow. It helps assess cash remaining after capital reinvestment, but does not establish the full amount available for distribution. Investors compare operating cash flow, capital expenditure and funding obligations; generic operating-company FCF is unsuitable as a primary bank valuation measure.');
define('current_ratio', 'Current Ratio',
  'อัตราส่วนสภาพคล่องหมุนเวียนคือสินทรัพย์หมุนเวียนหารด้วยหนี้สินหมุนเวียน ณ วันเดียวกัน ช่วยประเมินทรัพยากรระยะสั้นเทียบกับภาระที่ใกล้ถึงกำหนด แต่สินค้าคงเหลือและลูกหนี้อาจเปลี่ยนเป็นเงินสดได้ไม่ทัน นักลงทุนควรดูองค์ประกอบสินทรัพย์ กระแสเงินสด และกำหนดชำระหนี้ร่วมกัน โดยไม่ใช้เกณฑ์บริษัทพาณิชย์ตัดสินสภาพคล่องสถาบันการเงิน',
  'Current Ratio divides current assets by current liabilities at the same balance-sheet date. It assesses short-term resources against near-term obligations, but inventory and receivables may not convert to cash in time. Investors compare asset composition, operating cash flow and payment timing; conventional commercial-company liquidity rules are not primary measures for financial institutions.');
define('total_assets', 'Total Assets',
  'สินทรัพย์รวมคือมูลค่าทางบัญชีของทรัพยากรที่กิจการควบคุม ณ วันงบการเงิน รวมทั้งสินทรัพย์หมุนเวียนและไม่หมุนเวียน สะท้อนฐานทรัพยากรที่ใช้ดำเนินธุรกิจ แต่ไม่ใช่มูลค่าตลาดหรือเงินสดที่ใช้ได้ทั้งหมด นักลงทุนควรดูองค์ประกอบและคุณภาพสินทรัพย์ร่วมกับหนี้สิน ส่วนของผู้ถือหุ้น และความสามารถสร้างรายได้หรือกำไรจากฐานสินทรัพย์นั้น',
  'Total Assets is the carrying value of resources controlled by the business at the balance-sheet date, including current and non-current assets. It reflects the resource base, not market value or fully available cash. Investors assess asset composition and quality alongside liabilities, equity and the earnings generated from those resources.');
define('roic', 'ROIC',
  'ROIC คือผลตอบแทนจากกำไรดำเนินงานหลังภาษีเทียบกับเงินลงทุนเฉลี่ยตามวิธีคำนวณที่ตรวจสอบได้ สะท้อนประสิทธิภาพการใช้เงินทุนในกิจการหลัก นักลงทุนควรพิจารณาควบคู่กับกำไรดำเนินงาน ภาษี และองค์ประกอบฐานเงินลงทุน เพราะฐานทุนหรือวิธีคำนวณที่ต่างกันทำให้เปรียบเทียบคลาดเคลื่อน และไม่อาจสรุปการสร้างมูลค่าเหนือทุนได้หากไม่มีต้นทุนเงินทุนที่ตรวจสอบได้',
  'ROIC measures after-tax operating profit relative to average invested capital under the accepted methodology. It reflects the efficiency of deploying capital in the core business. Investors compare operating profit, tax inputs and the invested-capital base consistently; different denominators can distort comparisons, and value creation above the cost of capital requires separately verified cost-of-capital evidence.');
define('inventory', 'Inventory',
  'สินค้าคงเหลือคือมูลค่าทางบัญชีของวัตถุดิบ งานระหว่างทำ และสินค้าที่เตรียมขาย ณ วันงบการเงิน สะท้อนเงินทุนหมุนเวียนที่ผูกไว้กับการผลิตและการขาย นักลงทุนควรเทียบกับต้นทุนขาย รายได้ และการหมุนเวียนสินค้า เพราะยอดที่เพิ่มเพียงอย่างเดียวไม่ยืนยันว่าอุปสงค์อ่อนลงหรือกิจการกำลังเตรียมขยายกำลังผลิต',
  'Inventory is the carrying value of materials, work in progress and goods held for sale at the balance-sheet date. It reflects working capital tied up in production and sales. Investors compare cost of sales, revenue and inventory turnover because a higher balance alone proves neither weaker demand nor planned capacity expansion.');
define('dso', 'DSO',
  'DSO คือระยะเวลาเก็บเงินจากลูกหนี้การค้าโดยประมาณตามฐานรายได้และลูกหนี้ที่ใช้ในวิธีคำนวณ สะท้อนประสิทธิภาพการเก็บเงินและเงินทุนที่ค้างอยู่กับลูกค้า นักลงทุนควรดูเงื่อนไขเครดิต คุณภาพลูกหนี้ การเติบโตของรายได้ และกระแสเงินสด เพราะการเปลี่ยนแปลงตามฤดูกาลหรือฐานงวดอาจทำให้ระยะเวลาเก็บเงินดูต่างไป',
  'DSO estimates the collection period for trade receivables using the accepted revenue and receivables basis. It reflects collection efficiency and capital tied up with customers. Investors compare credit terms, receivable quality, revenue growth and operating cash flow because seasonality and period selection can affect the apparent collection time.');
define('quick_ratio', 'Quick Ratio',
  'อัตราส่วนสภาพคล่องเร็วตามวิธีคำนวณนี้ใช้เงินสด เงินลงทุนระยะสั้น และลูกหนี้การค้าเทียบกับหนี้สินหมุนเวียน สะท้อนทรัพยากรที่อาจใช้ชำระภาระระยะสั้นโดยไม่พึ่งขายสินค้าคงเหลือ นักลงทุนควรดูคุณภาพและความเร็วในการเก็บลูกหนี้ ข้อจำกัดการใช้เงินสด และกำหนดชำระหนี้ โดยไม่ใช้เป็นเกณฑ์หลักของสถาบันการเงิน',
  'Quick Ratio uses cash, short-term investments and trade receivables relative to current liabilities under the accepted methodology. It assesses short-term resources without relying on inventory sales. Investors compare receivable collectability, cash restrictions and payment timing; it is not a primary liquidity measure for financial institutions.');
define('cash|cash_and_equivalents', 'Cash and Cash Equivalents',
  'เงินสดและรายการเทียบเท่าเงินสดคือยอดเงินสดและเงินลงทุนที่เข้าเกณฑ์เทียบเท่าเงินสดตามรายการที่เลือก สะท้อนสภาพคล่องที่มีอยู่ ณ จุดเวลาของงบ ไม่ใช่เงินสดสุทธิหลังหักหนี้และไม่รวมเงินลงทุนระยะสั้นทุกประเภทโดยอัตโนมัติ นักลงทุนควรดูข้อจำกัดการใช้เงินสด ภาระหนี้ และกระแสเงินสดเพื่อประเมินความสามารถรองรับรายจ่าย',
  'Cash and Cash Equivalents is cash and qualifying near-cash holdings under the selected reported line at its balance-sheet date. It reflects liquidity, not net cash after debt, and does not automatically include all short-term investments. Investors compare cash restrictions, debt obligations and cash flows to assess spending capacity.');
define('cash_and_investments', 'Cash and Short-Term Investments',
  'เงินสดและเงินลงทุนระยะสั้นคือฐานเงินสดร่วมกับเงินลงทุนระยะสั้นตามวิธีรวมรายการที่ตรวจสอบได้ สะท้อนทรัพยากรสภาพคล่องที่กว้างกว่าเงินสดและรายการเทียบเท่าเงินสด แต่ยังไม่ได้หักหนี้จึงไม่ใช่สถานะเงินสดสุทธิ นักลงทุนควรดูความสามารถเปลี่ยนเงินลงทุนเป็นเงินสด ข้อจำกัดการใช้ และภาระหนี้ร่วมกัน',
  'Cash and Short-Term Investments combines accepted cash holdings and short-term investments. It reflects broader liquidity than cash equivalents alone, but has not deducted debt and is not Net Cash. Investors assess investment liquidity, restrictions and debt obligations together.');

// Related accounting lines share an economic explanation only where their
// reported scope remains explicit. No standalone / TTM / instant substitution.
function explain(keys: string, name: string, th: string, en: string, compareTh: string, compareEn: string) {
  define(keys, name, `${th} นักลงทุนควรพิจารณาร่วมกับ${compareTh} เพื่อประเมินคุณภาพและความต่อเนื่อง โดยใช้ขอบเขตรายการและฐานงวดเดียวกันก่อนเปรียบเทียบ.`,
    `${en} Investors compare ${compareEn} to assess quality and persistence, keeping the reported scope and period basis consistent.`);
}
explain('dividends_common', 'Common dividends paid', 'เงินปันผลหุ้นสามัญที่จ่ายจริงเป็นกระแสเงินสดออกตามงบ ไม่ใช่เงินปันผลที่เพิ่งประกาศหรือเงินปันผลแก่ผู้ถือหุ้นบุริมสิทธิ การไม่จ่ายปันผลอาจเป็นศูนย์จริงหากมีหลักฐานยืนยัน.', 'Common dividends paid are executed cash payments to common stockholders, separate from declarations and preferred dividends. A disclosed zero is valid data.', 'กระแสเงินสดอิสระ การซื้อหุ้นคืน และเงินสดคงเหลือ', 'free cash flow, executed repurchases and available liquidity');
explain('acquisitions', 'Business acquisition payments, net of cash acquired', 'เงินสดจ่ายเพื่อซื้อกิจการสุทธิจากเงินสดที่ได้มา เป็นการใช้เงินในกิจกรรมลงทุน ไม่ใช่มูลค่าดีลทั้งหมดหรือราคาอนุมัติซื้อกิจการ ต้องแยกจากเงินลงทุนในสินทรัพย์และการขายกิจการ.', 'Executed business acquisition cash payments net of cash acquired are investing cash uses, not total announced deal values or authorizations. Keep them separate from capital expenditure and disposal proceeds.', 'กระแสเงินสดอิสระ หนี้สิน และผลตอบแทนจากกิจการที่ซื้อ', 'free cash flow, debt financing and acquired-business returns');
explain('gross_profit', 'Gross Profit', 'กำไรขั้นต้นคือรายได้ที่เหลือหลังหักต้นทุนขาย สะท้อนผลตอบแทนจากสินค้าและบริการก่อนค่าใช้จ่ายดำเนินงาน จึงยังไม่ใช่กำไรสุทธิหรือเงินสด.', 'Gross Profit is revenue less cost of sales, reflecting product economics before operating expenses rather than net profit or cash.', 'รายได้ ต้นทุนขาย และค่าใช้จ่ายดำเนินงาน', 'revenue, cost of sales and operating expenses');
explain('operating_income', 'Operating Income', 'กำไรดำเนินงานคือรายได้หลังหักต้นทุนขายและค่าใช้จ่ายดำเนินงาน สะท้อนผลกำไรจากกิจการหลักก่อนผลของการจัดหาเงินและภาษี แต่ไม่ใช่กระแสเงินสด.', 'Operating Income measures profit after direct costs and operating expenses, before financing and tax effects; it is not operating cash flow.', 'รายได้ อัตรากำไรดำเนินงาน และเงินสดดำเนินงาน', 'revenue, operating margin and operating cash flow');
explain('cogs', 'Cost of Revenue', 'ต้นทุนขายคือต้นทุนที่กิจการรับรู้สำหรับสินค้าและบริการที่ขายในงวด สะท้อนต้นทุนโดยตรงของยอดขาย โดยขอบเขตขึ้นกับนโยบายบัญชีและไม่ใช่ค่าใช้จ่ายดำเนินงานทุกประเภท.', 'Cost of Revenue measures recognized costs of goods and services sold in the period. Its accounting scope differs from the full operating expense base.', 'รายได้ กำไรขั้นต้น และส่วนผสมสินค้า', 'revenue, gross profit and product mix');
explain('opex|operating_expenses', 'Operating Expenses', 'ค่าใช้จ่ายดำเนินงานคือค่าใช้จ่ายที่อยู่ในรายการดำเนินงานตามขอบเขตของงบ สะท้อนต้นทุนสนับสนุนการขายและบริหารกิจการ โดยต้องแยกจากต้นทุนขายและตรวจว่ารายการย่อยรวมอะไรบ้าง.', 'Operating Expenses measures the reported operating cost line. It reflects the cost base supporting the business, with line scope checked separately from cost of sales.', 'รายได้ กำไรดำเนินงาน และองค์ประกอบค่าใช้จ่าย', 'revenue, operating income and expense components');
explain('research_and_development', 'Research and Development', 'ค่าใช้จ่ายวิจัยและพัฒนาคือต้นทุนด้านการพัฒนาสินค้า เทคโนโลยี หรือองค์ความรู้ที่รับรู้เป็นค่าใช้จ่าย สะท้อนทรัพยากรที่ใช้สนับสนุนอนาคต แต่ยอดสูงไม่ได้ยืนยันความสำเร็จหรือความได้เปรียบ.', 'Research and Development measures recognized expenditure on developing products, technology or knowledge. It reflects investment effort, not proof of successful innovation or a moat.', 'รายได้ กำไรดำเนินงาน และหลักฐานผลลัพธ์การพัฒนา', 'revenue, operating income and evidence of development outcomes');
explain('selling_general_administrative', 'Selling, General and Administrative', 'ค่าใช้จ่ายขายและบริหารคือต้นทุนสนับสนุนการขายและการบริหารที่รับรู้ตามบัญชี สะท้อนภาระโครงสร้างของกิจการ การลดค่าใช้จ่ายไม่จำเป็นต้องดีหากกระทบความสามารถดำเนินธุรกิจ.', 'Selling, General and Administrative measures recognized selling and corporate support costs. It reflects overhead structure; reductions are not inherently favorable if they weaken operating capacity.', 'รายได้ กำไรดำเนินงาน และขอบเขตค่าใช้จ่าย', 'revenue, operating income and expense scope');
explain('interest_income|other_income', 'Non-operating Income', 'รายการรายได้ดอกเบี้ยหรือรายได้อื่นสะท้อนผลตอบแทนตามประเภทที่ระบุในงบ ซึ่งอาจอยู่นอกกิจการหลักหรือเกิดไม่สม่ำเสมอ ต้องอ่านชื่อรายการให้ตรงก่อนประเมิน ไม่รวมเป็นยอดขายโดยอัตโนมัติ.', 'The selected interest or other-income line measures the return identified in the statement. It can differ from core sales and may be non-recurring; its reported scope must be kept distinct from revenue.', 'กำไรดำเนินงาน เงินลงทุน และความต่อเนื่องของรายการ', 'operating income, investments and recurrence');
explain('interest_expense', 'Interest Expense', 'ค่าใช้จ่ายดอกเบี้ยคือต้นทุนการจัดหาเงินที่รับรู้ในงวด สะท้อนภาระของหนี้และเงื่อนไขเงินทุน แต่ไม่เท่ากับเงินสดชำระหนี้ทั้งหมด.', 'Interest Expense is the recognized financing cost for the period. It reflects debt funding burden, not the full cash repayment of principal.', 'หนี้ที่มีดอกเบี้ย กำไรดำเนินงาน และกระแสเงินสด', 'interest-bearing debt, operating profit and cash flow');
explain('income_before_tax', 'Pretax Income', 'กำไรก่อนภาษีคือผลกำไรหลังรายได้และค่าใช้จ่ายก่อนภาษีเงินได้ สะท้อนผลการทำกำไรรวมผลการจัดหาเงิน โดยยังไม่ใช่กำไรที่เป็นของผู้ถือหุ้นหลังภาษี.', 'Pretax Income measures profit after recognized income and expenses but before income tax. It includes financing effects and differs from after-tax shareholder earnings.', 'กำไรดำเนินงาน ดอกเบี้ย และภาษี', 'operating income, interest and tax');
explain('income_tax_expense|tax_rate', 'Income Tax', 'ภาษีเงินได้และอัตราภาษีที่เกี่ยวข้องสะท้อนภาระภาษีตามบัญชี โดยอัตราต้องยึดตัวเศษและกำไรก่อนภาษีตามวิธีคำนวณที่กำหนด รายการภาษีเงินสดและภาษีรอการตัดบัญชีอาจต่างกัน.', 'The selected income-tax amount or rate reflects the accounting tax burden. A rate retains its accepted pretax-income denominator; recognized tax can differ from cash tax because of deferred items.', 'กำไรก่อนภาษี ภาษีเงินสด และรายการภาษีรอการตัดบัญชี', 'pretax income, cash tax and deferred-tax items');
explain('net_margin', 'Net Margin', 'อัตรากำไรสุทธิคือกำไรสุทธิเทียบกับรายได้ สะท้อนยอดขายที่เหลือเป็นกำไรหลังค่าใช้จ่าย ดอกเบี้ย และภาษี โดยยังไม่ยืนยันการแปลงเป็นเงินสด.', 'Net Margin measures net income relative to revenue after expenses, financing and tax. It reflects bottom-line profitability, not cash conversion.', 'อัตรากำไรดำเนินงาน ภาษี และเงินสดดำเนินงาน', 'operating margin, tax and operating cash flow');
explain('ebitda|ebitda_margin', 'EBITDA', 'EBITDA และอัตรากำไรที่อิง EBITDA ใช้กำไรดำเนินงานบวกค่าเสื่อมราคาและค่าตัดจำหน่ายตามวิธีที่กำหนด หากเลือกอัตราส่วนต้องเทียบกับรายได้ ช่วยดูผลกำไรก่อนรายการไม่ใช่เงินสดบางชนิด แต่ไม่ใช่กระแสเงินสดหรือเงินสดหลังการลงทุน.', 'EBITDA adds accepted depreciation and amortization to operating income under this methodology; the margin expresses that amount relative to revenue. It excludes selected non-cash expenses but is not operating or free cash flow.', 'ค่าเสื่อมราคา รายจ่ายฝ่ายทุน และกระแสเงินสด', 'depreciation, capital expenditure and cash flows');
explain('eps|eps_diluted', 'Diluted EPS', 'กำไรต่อหุ้นปรับลดคือกำไรที่จัดสรรให้หุ้นสามัญเทียบกับจำนวนหุ้นเฉลี่ยปรับลดตามวิธีบัญชี สะท้อนกำไรต่อสิทธิความเป็นเจ้าของ โดยอาจเปลี่ยนจากกำไรหรือจำนวนหุ้นที่เปลี่ยน ไม่ใช่กระแสเงินสดต่อหุ้น.', 'Diluted EPS measures earnings attributable to common shareholders per diluted weighted-average share under the reported methodology. It reflects earnings per ownership unit, influenced by both earnings and share count, rather than cash per share.', 'กำไรสุทธิ จำนวนหุ้น และการออกหรือซื้อหุ้นคืน', 'net income, share count and issuance or repurchases');
explain('total_current_assets|current_assets|non_current_assets', 'Assets by Maturity', 'สินทรัพย์ในรายการนี้แยกตามการจัดประเภทหมุนเวียนหรือไม่หมุนเวียนในงบ สะท้อนทรัพยากรที่ถือเพื่อใช้หรือเปลี่ยนเป็นเงินตามขอบเขตที่เลือก ยอดรวมไม่ยืนยันความเร็วหรือราคาที่ขายได้จริง.', 'The selected asset line retains its reported current or non-current classification. It reflects resources within that maturity scope, not proof of cash-conversion speed or realizable market value.', 'องค์ประกอบสินทรัพย์ หนี้สินที่ถึงกำหนด และกระแสเงินสด', 'asset composition, obligation timing and cash flow');
explain('receivables|accounts_receivable', 'Accounts Receivable', 'ลูกหนี้การค้าคือสิทธิเรียกเก็บเงินจากลูกค้าตามมูลค่าทางบัญชีของรายการ สะท้อนยอดขายที่ยังไม่เปลี่ยนเป็นเงินสด จึงต้องดูความสามารถเรียกเก็บและค่าเผื่อหนี้เสีย.', 'Accounts Receivable is the carrying value of amounts owed by customers. It reflects sales not yet converted to cash and depends on collectability and loss allowances.', 'รายได้ DSO และเงินสดดำเนินงาน', 'revenue, DSO and operating cash flow');
explain('payables|accounts_payable', 'Accounts Payable', 'เจ้าหนี้การค้าคือภาระที่ต้องจ่ายให้ผู้ขายตามรายการในงบ สะท้อนการจัดหาเงินทุนหมุนเวียนผ่านเครดิตจากคู่ค้า ยอดสูงอาจเกี่ยวกับขนาดกิจการหรือจังหวะชำระ ไม่ยืนยันปัญหาสภาพคล่องลำพัง.', 'Accounts Payable measures obligations to suppliers under the reported line. It reflects trade-credit funding and payment timing; a higher balance alone does not establish liquidity distress.', 'ต้นทุนขาย DPO และกระแสเงินสด', 'cost of sales, DPO and cash flow');
explain('short_term_investments', 'Short-Term Investments', 'เงินลงทุนระยะสั้นคือเงินลงทุนตามประเภทและอายุที่ระบุในงบ สะท้อนการจัดสรรทรัพยากรส่วนหนึ่งเพื่อผลตอบแทนและสภาพคล่อง แต่ไม่ใช่เงินสดเทียบเท่าทุกรายการ.', 'Short-Term Investments measures investments within the reported short-term classification. It reflects a source of returns and potential liquidity, but is not automatically cash equivalents.', 'เงินสด อายุเงินลงทุน และความเสี่ยงการเปลี่ยนเป็นเงินสด', 'cash, investment maturity and liquidity risk');
explain('net_ppe|operating_lease_rou_assets', 'Operating Asset Base', 'สินทรัพย์ดำเนินงานในรายการนี้เป็นมูลค่าทางบัญชีของทรัพย์สินหรือสิทธิใช้งานตามชื่อที่ระบุ สะท้อนทรัพยากรที่รองรับการผลิตหรือบริการ โดยต้องแยกกรรมสิทธิ์ออกจากสิทธิใช้งานที่ได้จากสัญญาเช่า.', 'The selected operating-asset line measures the carrying value of property or lease rights specified by its label. It reflects production or service capacity, keeping owned assets distinct from leased rights.', 'รายจ่ายฝ่ายทุน ค่าเสื่อมราคา และภาระสัญญาเช่า', 'capital expenditure, depreciation and lease obligations');
explain('goodwill', 'Goodwill', 'ค่าความนิยมคือสินทรัพย์จากการซื้อกิจการตามการจัดสรรราคาซื้อในบัญชี สะท้อนราคาที่จ่ายเหนือสินทรัพย์สุทธิที่ระบุได้ ไม่ใช่เงินสดและไม่ยืนยันความได้เปรียบที่คงอยู่.', 'Goodwill is the acquisition-related carrying amount arising from purchase-price allocation. It reflects value paid beyond identifiable net assets, not cash or proof of a lasting competitive advantage.', 'ผลตอบแทนการซื้อกิจการ การด้อยค่า และส่วนของผู้ถือหุ้น', 'acquisition returns, impairment and equity');
explain('total_liabilities|total_current_liabilities|current_liabilities|non_current_liabilities|accrued_and_other_current_liabilities', 'Liabilities', 'หนี้สินตามรายการที่เลือกคือภาระผูกพันทางบัญชีในขอบเขตและอายุที่งบกำหนด สะท้อนสิทธิเรียกร้องของคู่ค้า เจ้าหนี้ หรือผู้เกี่ยวข้อง ไม่เท่ากับหนี้ที่มีดอกเบี้ยทั้งหมดโดยอัตโนมัติ.', 'The selected liability line measures recognized obligations within its reported scope and maturity. It reflects claims on business resources and is not automatically identical to interest-bearing debt.', 'สินทรัพย์ กระแสเงินสด และกำหนดชำระภาระ', 'assets, cash flows and obligation timing');
explain('total_debt|short_term_debt|long_term_debt|long_term_debt_and_finance_leases|current_debt_and_finance_leases|noncurrent_debt_and_finance_leases', 'Debt', 'หนี้ตามรายการที่เลือกใช้ขอบเขตหนี้ที่มีดอกเบี้ยและสัญญาเช่าการเงินตามนิยามที่กำหนด พร้อมอายุหมุนเวียนหรือไม่หมุนเวียนเมื่อระบุ สะท้อนภาระจัดหาเงินทุน ไม่ควรนำหนี้สินรวมมาแทนหรือรวมรายการซ้ำ.', 'The selected debt line retains the accepted scope of interest-bearing debt and finance leases, including maturity classification where specified. It reflects funding obligations; total liabilities cannot replace debt and overlapping lines must not be double counted.', 'เงินสด ดอกเบี้ย กระแสเงินสด และตารางครบกำหนด', 'cash, interest, cash flow and maturity schedules');
explain('finance_lease_liabilities_current|finance_lease_liabilities_non_current|finance_lease_payments', 'Finance Lease', 'รายการสัญญาเช่าการเงินสะท้อนภาระหรือการชำระเงินตามประเภทที่ชื่อรายการระบุ ต้องแยกยอดคงเหลือ ณ วันงบจากเงินสดที่จ่ายในงวด และแยกส่วนหมุนเวียนจากไม่หมุนเวียนก่อนรวมภาระหนี้.', 'The selected finance-lease line measures the obligation or payment specified by its label. Outstanding balances, period cash payments and maturity classifications are distinct and must be kept separate when assessing debt.', 'หนี้ เงินสด และกำหนดชำระตามสัญญา', 'debt, cash and contractual payment timing');
explain('operating_lease_liabilities|operating_lease_liabilities_current|operating_lease_liabilities_non_current', 'Operating Lease Liabilities', 'หนี้สินสัญญาเช่าดำเนินงานคือภาระเช่าตามมูลค่าที่รับรู้ในงบและอายุที่ระบุ สะท้อนข้อผูกพันการใช้สินทรัพย์ในอนาคต ไม่ควรรวมเป็นหนี้การเงินโดยขัดกับนโยบายหนี้ที่กำหนด.', 'Operating Lease Liabilities measures recognized operating-lease obligations within the specified maturity scope. It reflects contracted asset-use commitments and must follow the accepted debt-inclusion policy rather than automatically being treated as financing debt.', 'สิทธิใช้งานสินทรัพย์ กระแสเงินสด และตารางค่าเช่า', 'right-of-use assets, cash flow and lease schedules');
explain('total_equity|stockholders_equity|common_equity|preferred_equity|noncontrolling_interest|redeemable_noncontrolling_interest', 'Equity', 'ทุนในรายการที่เลือกคือสิทธิในสินทรัพย์สุทธิตามการจัดสรรให้เจ้าของแต่ละประเภทในงบ สะท้อนฐานทุนทางบัญชีซึ่งต่างจากมูลค่าตลาด ต้องแยกทุนสามัญ ทุนบุริมสิทธิ และส่วนได้เสียที่ไม่มีอำนาจควบคุมให้ตรงรายการ.', 'The selected equity line measures the book interest allocated to the ownership class specified by the statement. It reflects accounting capital, not market value; common, preferred and noncontrolling interests retain distinct scopes.', 'สินทรัพย์ หนี้สิน กำไรที่จัดสรร และฐานผลตอบแทนทุน', 'assets, liabilities, attributed earnings and return denominators');
explain('common_stock|additional_paid_in_capital|retained_earnings|aoci', 'Equity Components', 'องค์ประกอบส่วนของผู้ถือหุ้นนี้แสดงแหล่งที่มาหรือผลสะสมของทุนตามชื่อรายการ เช่น เงินทุนที่ชำระ กำไรสะสม หรือกำไรขาดทุนเบ็ดเสร็จอื่น สะท้อนโครงสร้างทุน ไม่ใช่ยอดเงินสดที่พร้อมแจกจ่ายและไม่ควรสลับแต่ละองค์ประกอบกัน.', 'The selected equity component identifies contributed capital, retained earnings or other comprehensive results according to its reported label. It reflects capital composition, not immediately distributable cash, and components are not interchangeable.', 'ส่วนของผู้ถือหุ้นรวม เงินปันผล และการเปลี่ยนแปลงทุน', 'total equity, dividends and changes in capital');
explain('depreciation|da|depreciation_amortization_and_accretion|depreciation_amortization_and_impairment|depreciation_expense|amortization_of_intangibles', 'Depreciation and Amortization', 'รายการนี้สะท้อนการจัดสรรต้นทุนสินทรัพย์หรือการปรับมูลค่าที่ไม่ใช่เงินสดตามขอบเขตที่ชื่อรายการระบุ ต้องแยกค่าเสื่อมราคา ค่าตัดจำหน่าย การเพิ่มมูลค่า และการด้อยค่า ไม่ถือว่าทุกชื่อเป็นรายการเดียวกัน.', 'The selected line measures non-cash asset-cost allocation or value adjustments within its exact reported scope. Depreciation, amortization, accretion and impairment are distinct and must not be substituted merely because all affect non-cash adjustments.', 'ฐานสินทรัพย์ รายจ่ายฝ่ายทุน และกระแสเงินสด', 'asset balances, capital expenditure and cash flow');
explain('sbc|stock_based_compensation', 'Stock-Based Compensation', 'ค่าตอบแทนที่ใช้หุ้นคือค่าใช้จ่ายตามบัญชีจากการให้สิทธิในหุ้นแก่พนักงานหรือผู้เกี่ยวข้อง สะท้อนต้นทุนที่ไม่จ่ายเงินสดในขณะรับรู้ แต่ยังมีผลทางเศรษฐกิจต่อผู้ถือหุ้นผ่านสิทธิและการปรับลด.', 'Stock-Based Compensation measures recognized expense for equity-based awards. It can be non-cash at recognition but still has an economic cost through ownership rights and dilution.', 'กำไร จำนวนหุ้น และการซื้อหุ้นคืน', 'earnings, share count and repurchases');
explain('capex', 'Capital Expenditure', 'รายจ่ายฝ่ายทุนคือเงินสดจ่ายลงทุนในสินทรัพย์ถาวรตามขอบเขตที่กำหนด สะท้อนเงินที่ใช้รักษาหรือขยายทรัพยากรดำเนินงาน แต่ยอดเดียวไม่แยกการลงทุนบำรุงรักษาออกจากการเติบโต.', 'Capital Expenditure measures the accepted cash outflow for capital assets. It reflects reinvestment in operating resources but does not by itself separate maintenance from growth spending.', 'เงินสดดำเนินงาน ฐานสินทรัพย์ และ FCF', 'operating cash flow, asset balances and FCF');
explain('icf|investing_cash_flow', 'Investing Cash Flow', 'กระแสเงินสดจากการลงทุนคือเงินสดสุทธิของกิจกรรมลงทุนในงวด รวมรายการตามขอบเขตงบที่อาจมีสินทรัพย์ การซื้อกิจการ หรือหลักทรัพย์ สะท้อนการจัดสรรเงินทุน ไม่ใช่รายจ่ายฝ่ายทุนรายการเดียว และเงินสดติดลบไม่ยืนยันผลลงทุนที่ไม่ดี.', 'Investing Cash Flow is net cash from reported investing activities, potentially including assets, acquisitions and securities. It reflects capital allocation, not just capital expenditure; an outflow alone does not establish poor investment quality.', 'องค์ประกอบรายการลงทุน เงินสดดำเนินงาน และหนี้', 'investment components, operating cash flow and debt');
explain('fcf_financing|financing_cash_flow|other_financing', 'Financing Cash Flow', 'รายการกระแสเงินสดจัดหาเงินสะท้อนเงินสดจากผู้ให้ทุนหรือการคืนทุนตามขอบเขตที่ระบุ เช่น การกู้ยืม หุ้น และเงินปันผล โดยยอดสุทธิหรือรายการอื่นต้องแยกจากแต่ละองค์ประกอบ สะท้อนวิธีสนับสนุนกิจการ ไม่ใช่ความสามารถทำกำไร.', 'The selected financing cash-flow line measures funding or capital returns within its reported scope, including debt, equity or distributions where applicable. Net and residual lines differ from their components; funding activity does not establish operating profitability.', 'เงินสดดำเนินงาน การลงทุน และโครงสร้างทุน', 'operating cash flow, investment and capital structure');
explain('dividends_paid|distributions_to_noncontrolling_interests|dividends_to_noncontrolling_interests|distributions_to_noncontrolling_and_redeemable_interests', 'Cash Distributions', 'รายการจ่ายผลตอบแทนนี้คือเงินสดที่ส่งให้ผู้ถือสิทธิตามประเภทที่งบระบุ ต้องแยกเงินปันผลหุ้นสามัญออกจากการจ่ายให้ส่วนได้เสียอื่น สะท้อนการคืนทุน ไม่ใช่ข้อยืนยันว่าจ่ายได้ต่อเนื่อง.', 'The selected cash-distribution line measures payments to the ownership class identified in the statement. Common dividends and distributions to other interests are distinct; a payment alone does not establish sustainability.', 'เงินสดดำเนินงาน FCF และภาระหนี้', 'operating cash flow, FCF and debt commitments');
explain('repurchase_of_common_stock|issuance_of_common_stock|equity_issuance_proceeds|option_exercise_proceeds|equity_compensation_and_option_proceeds', 'Equity Cash Flows', 'รายการหุ้นนี้สะท้อนเงินสดจากการออกหุ้น การใช้สิทธิ หรือการซื้อหุ้นคืนตามชื่อที่เลือก ต้องแยกทิศทางเงินรับและเงินจ่าย สะท้อนการจัดสรรทุนและสิทธิความเป็นเจ้าของ ไม่ใช่กำไรจากกิจการ.', 'The selected equity cash-flow line measures issuance, option proceeds or repurchases as specified by its label. Inflows and outflows retain their direction; these financing actions affect capital allocation and ownership, not operating earnings.', 'จำนวนหุ้น กำไรต่อหุ้น และสภาพคล่อง', 'share count, EPS and liquidity');
explain('debt_issuance|debt_repayments|debt_issuance_payments', 'Debt Funding Cash Flows', 'รายการเงินสดเกี่ยวกับหนี้นี้คือเงินรับจากการกู้ เงินจ่ายชำระ หรือยอดสุทธิตามชื่อที่ระบุ สะท้อนกิจกรรมจัดหาเงินทุนในงวด ไม่ใช่ยอดหนี้คงเหลือและไม่ใช่รายได้.', 'The selected debt cash-flow line measures borrowing proceeds, repayments or their net amount as labeled. It reflects funding activity over a period, not the outstanding debt balance or revenue.', 'ยอดหนี้ ดอกเบี้ย และเงินสดที่มีอยู่', 'debt balances, interest and available cash');
explain('change_receivables|change_inventory|change_payables|change_working_capital|non_cash_items', 'Operating Cash Reconciliation', 'รายการปรับกระแสเงินสดนี้สะท้อนผลของเงินทุนหมุนเวียนหรือรายการไม่ใช่เงินสดตามขอบเขตที่เลือกในการกระทบยอดกำไรเป็นเงินสด เครื่องหมายในงบอาจต่างจากการเปลี่ยนยอดงบดุล จึงไม่ควรสลับกันโดยตรง.', 'The selected reconciliation line measures working-capital or non-cash effects within the operating cash-flow bridge. Cash-flow signs can differ from balance-sheet movements, so those observations are not directly interchangeable.', 'กำไรสุทธิ กระแสเงินสดดำเนินงาน และรายการงบดุลที่เกี่ยวข้อง', 'net income, operating cash flow and the corresponding balance-sheet items');
explain('exchange_rate_effect|net_change_cash', 'Cash Balance Bridge', 'รายการสะพานเงินสดนี้คือผลอัตราแลกเปลี่ยนหรือการเปลี่ยนเงินสดสุทธิตามชื่อที่ระบุ ช่วยอธิบายความต่างระหว่างเงินสดต้นงวดกับปลายงวด แต่ผลแปลงค่าเงินไม่ใช่เงินสดจากกิจการหลัก.', 'The selected cash bridge line measures exchange-rate effects or the net cash change as labeled. It explains the movement between opening and closing cash; currency translation is not operating cash generation.', 'เงินสดต้นงวด ปลายงวด และกระแสเงินสดแต่ละกิจกรรม', 'opening cash, closing cash and the cash-flow categories');
explain('prepaid_and_other_current_assets|current_deferred_liabilities', 'Timing-related Balance Sheet Items', 'รายการนี้สะท้อนทรัพยากรจ่ายล่วงหน้าหรือภาระที่รอรับรู้ตามขอบเขตงบที่ชื่อระบุ จึงเกี่ยวกับจังหวะเงินสดและการรับรู้รายได้หรือค่าใช้จ่าย ไม่ควรถือว่าสินทรัพย์และหนี้สินรอการรับรู้เป็นประเภทเดียวกัน.', 'The selected line reflects prepaid resources or deferred obligations within its reported scope. It concerns timing between cash and income or expense recognition; prepaid assets and deferred liabilities are distinct.', 'รายการรายได้ ค่าใช้จ่าย และเงินสดที่เกี่ยวข้อง', 'related revenue, expenses and cash movements');
explain('cash_and_restricted_cash|cash_and_restricted_cash_including_disposal_group', 'Cash Including Restricted Cash', 'รายการเงินสดนี้รวมเงินสดที่มีข้อจำกัดตามขอบเขตที่ระบุ รวมกลุ่มสินทรัพย์เพื่อจำหน่ายเมื่อชื่อรายการกำหนด สะท้อนฐานเงินสดเพื่อกระทบยอด แต่ไม่ใช่เงินสดทั้งหมดที่ใช้ชำระภาระได้อย่างอิสระ.', 'This cash line includes restricted cash within its reported scope and disposal-group amounts where specified. It supports cash reconciliation but is not entirely unrestricted liquidity available to meet obligations.', 'เงินสดที่ใช้ได้จริง ข้อจำกัด และฐานกระทบยอดงบเงินสด', 'unrestricted liquidity, restrictions and the cash-flow reconciliation scope');
explain('non_interest_income', 'Non-interest Income', 'รายได้ที่ไม่ใช่ดอกเบี้ยคือรายได้ค่าธรรมเนียมหรือกิจกรรมอื่นตามรายการของธุรกิจการเงิน สะท้อนแหล่งรายได้ที่ต่างจากส่วนต่างดอกเบี้ย โดยแต่ละองค์ประกอบอาจมีความต่อเนื่องและความเสี่ยงต่างกัน.', 'Non-interest Income measures financial-sector fee and other revenue within the reported line. It reflects income beyond interest spreads, whose components can differ in recurrence and risk.', 'องค์ประกอบค่าธรรมเนียม รายได้ดอกเบี้ยสุทธิ และค่าใช้จ่าย', 'fee components, net interest income and operating expenses');
explain('provision_for_credit_losses', 'Provision for Credit Losses', 'ค่าใช้จ่ายสำรองผลขาดทุนเครดิตคือผลที่รับรู้ในงวดเพื่อสะท้อนความเสี่ยงการเรียกเก็บตามวิธีบัญชี สะท้อนต้นทุนความเสี่ยงสินเชื่อ ไม่เท่ากับหนี้เสียที่ตัดออกหรือยอดสำรองคงเหลือ.', 'Provision for Credit Losses measures the period expense recognized for expected credit risk under the accounting method. It reflects the cost of credit risk, not charge-offs or the outstanding allowance balance.', 'พอร์ตสินเชื่อ คุณภาพเครดิต และยอดสำรอง', 'loan exposures, credit quality and allowance balances');
explain('efficiency_ratio', 'Efficiency Ratio', 'อัตราประสิทธิภาพของธุรกิจการเงินใช้ค่าใช้จ่ายเทียบกับรายได้ตามสูตรที่กำหนด สะท้อนภาระต้นทุนต่อรายได้ แต่รายการพิเศษและวิธีปรับรายได้อาจทำให้เทียบต่างบริษัทคลาดเคลื่อน.', 'Efficiency Ratio compares financial-sector expenses with the accepted revenue basis. It reflects the cost burden of generating income; exceptional items and adjusted definitions can impair peer comparisons.', 'รายได้ ค่าใช้จ่าย และวิธีปรับรายการพิเศษ', 'revenue, expenses and exceptional-item adjustments');

// Ratios and sector measures keep their own numerator, denominator and role.
// A shared family description is insufficient for the selected metric box.
explain('beginning_cash', 'Beginning Cash Balance', 'เงินสดต้นงวดคือยอดที่ใช้เริ่มกระทบยอดงบกระแสเงินสดตามขอบเขตเงินสดของงบนั้น ซึ่งอาจรวมเงินสดที่มีข้อจำกัดเมื่อวิธีที่รายงานกำหนด สะท้อนฐานเริ่มต้น ไม่ใช่เงินสดสุทธิหลังหักหนี้หรือเงินสดดำเนินงานในงวด.', 'Beginning Cash Balance is the opening balance used for cash-flow reconciliation under the reported cash scope, including restricted cash where that basis requires it. It is neither net cash after debt nor period operating cash flow.', 'ยอดปลายงวดก่อนหน้า ขอบเขตเงินสด และการเปลี่ยนเงินสดในงวด', 'the preceding closing balance, cash scope and period cash movements');
explain('ending_cash', 'Ending Cash Balance', 'เงินสดปลายงวดคือยอดที่ใช้ปิดการกระทบยอดงบกระแสเงินสดตามฐานของงบนั้น ซึ่งอาจรวมเงินสดที่มีข้อจำกัดตามวิธีรายงาน สะท้อนยอดหลังการรับจ่ายและผลแปลงค่าเงิน ไม่ควรแทนด้วยเงินสดที่ใช้ได้อิสระหรือสถานะเงินสดสุทธิ.', 'Ending Cash Balance is the closing balance used by the cash-flow statement on its reported cash basis, including restricted cash where required. It reflects receipts, payments and translation effects, not necessarily unrestricted liquidity or net cash after debt.', 'เงินสดต้นงวด กระแสเงินสด ผลแปลงค่าเงิน และข้อจำกัดการใช้', 'opening cash, cash flows, translation effects and restrictions');
explain('roe', 'ROE', 'ROE คือกำไรที่จัดสรรให้หุ้นสามัญเทียบกับส่วนของผู้ถือหุ้นสามัญเฉลี่ยตามวิธีคำนวณ สะท้อนผลตอบแทนต่อทุนผู้ถือหุ้น แต่หนี้เพิ่มหรือฐานทุนลดอาจทำให้อัตราสูงโดยกิจการไม่ได้ดีขึ้น.', 'ROE compares accepted common earnings with average common equity. It measures returns on shareholder capital; leverage or a shrinking equity base can raise the ratio without improving operating economics.', 'กำไรสามัญ ฐานทุนเฉลี่ย และโครงสร้างหนี้', 'common earnings, average common equity and leverage');
explain('roa', 'ROA', 'ROA คือกำไรเทียบกับสินทรัพย์เฉลี่ยตามฐานงวดที่เข้ากันได้ สะท้อนความสามารถสร้างผลตอบแทนจากทรัพยากรทั้งหมด โดยองค์ประกอบสินทรัพย์แต่ละอุตสาหกรรมทำให้เปรียบเทียบข้ามธุรกิจได้จำกัด.', 'ROA compares accepted earnings with a compatible average asset base. It measures the profitability of business resources, with asset composition limiting comparisons across sectors.', 'กำไร สินทรัพย์เฉลี่ย และองค์ประกอบสินทรัพย์', 'earnings, average assets and asset composition');
explain('debt_to_equity', 'Debt to Equity', 'อัตราหนี้ต่อทุนคือหนี้ตามนิยามที่กำหนดเทียบกับส่วนของผู้ถือหุ้น สะท้อนการพึ่งเงินกู้เทียบกับฐานทุนเจ้าของ แต่ทุนที่เล็กหรือติดลบทำให้อัตราตีความได้จำกัดและไม่ยืนยันความสามารถชำระหนี้.', 'Debt to Equity compares canonical debt with the accepted equity base. It reflects borrowing relative to owner capital; a small or negative equity denominator limits interpretation and does not prove repayment capacity.', 'ขอบเขตหนี้ ส่วนของผู้ถือหุ้น เงินสด และกำหนดชำระ', 'debt scope, equity, cash and maturities');
explain('debt_to_asset', 'Debt to Assets', 'อัตราหนี้ต่อสินทรัพย์คือหนี้ตามนิยามที่กำหนดเทียบกับสินทรัพย์รวม สะท้อนภาระหนี้เมื่อเทียบกับฐานทรัพยากร แต่สินทรัพย์อาจไม่เปลี่ยนเป็นเงินสดได้ตามมูลค่าบัญชี.', 'Debt to Assets compares canonical debt with total assets. It assesses funding burden relative to the resource base, whose book value does not establish liquidation proceeds or immediate liquidity.', 'คุณภาพสินทรัพย์ เงินสด กระแสเงินสด และหนี้ที่ครบกำหนด', 'asset quality, cash, cash flow and maturities');
explain('equity_ratio', 'Equity Ratio', 'อัตราส่วนทุนคือส่วนของผู้ถือหุ้นรวมส่วนได้เสียที่ไม่มีอำนาจควบคุมเทียบกับสินทรัพย์รวม สะท้อนสัดส่วนฐานทรัพยากรที่มีทุนรองรับ ไม่ใช่ผลตอบแทนทุนสามัญหรืออัตราสภาพคล่อง.', 'Equity Ratio compares total equity including noncontrolling interests with total assets. It reflects the equity share of the resource base, not common-equity returns or cash liquidity.', 'ส่วนของผู้ถือหุ้นรวม หนี้สิน และคุณภาพสินทรัพย์', 'total equity, liabilities and asset quality');
explain('debt_to_ebitda', 'Debt to EBITDA', 'อัตราหนี้ต่อ EBITDA คือภาระหนี้เทียบกับ EBITDA ตามฐานงวดที่กำหนด ช่วยดูหนี้เทียบกับกำไรก่อนรายการที่วิธีคำนวณตัดออก แต่ EBITDA ไม่ใช่เงินสดชำระหนี้และค่าติดลบทำให้อัตราใช้ได้จำกัด.', 'Debt to EBITDA compares the accepted debt balance with period-compatible EBITDA. It assesses leverage relative to that earnings proxy, which is not cash available for repayment; a non-positive denominator limits its use.', 'เงินสด ดอกเบี้ย CapEx และกำหนดชำระหนี้', 'cash, interest, capital expenditure and maturities');
explain('fcf_to_sales', 'FCF to Sales', 'อัตรา FCF ต่อรายได้คือกระแสเงินสดอิสระตามนิยามที่กำหนดเทียบกับรายได้งวดเดียวกัน สะท้อนยอดขายที่แปลงเป็นเงินสดหลังการลงทุน แต่จังหวะเงินทุนหมุนเวียนและ CapEx อาจทำให้อัตราผันผวน.', 'FCF to Sales compares accepted free cash flow with revenue for a compatible period. It measures sales conversion into post-investment cash, which can fluctuate with working-capital and capital-spending timing.', 'เงินสดดำเนินงาน รายจ่ายฝ่ายทุน และรายได้', 'operating cash flow, capital expenditure and revenue');
explain('fcf_to_net_income', 'FCF to Net Income', 'อัตรา FCF ต่อกำไรสุทธิคือกระแสเงินสดอิสระเทียบกับกำไรสุทธิบนฐานงวดเดียวกัน สะท้อนความสัมพันธ์ระหว่างกำไรบัญชีกับเงินสดหลังลงทุน โดยกำไรสุทธิที่ต่ำหรือติดลบทำให้อัตราไม่เหมาะใช้สรุปคุณภาพกำไรลำพัง.', 'FCF to Net Income compares free cash flow with net income on a compatible period basis. It assesses post-investment cash relative to accounting earnings; a small or negative earnings denominator can make the ratio misleading.', 'กำไร รายการไม่ใช่เงินสด เงินทุนหมุนเวียน และ CapEx', 'earnings, non-cash adjustments, working capital and capital expenditure');
explain('asset_turnover', 'Asset Turnover', 'อัตราหมุนเวียนสินทรัพย์คือรายได้เทียบกับสินทรัพย์เฉลี่ยตามวิธีคำนวณ สะท้อนยอดขายที่สร้างจากฐานทรัพยากร แต่ไม่บอกกำไรจากยอดขายและธุรกิจใช้สินทรัพย์มากน้อยต่างกัน.', 'Asset Turnover compares revenue with average assets under the accepted methodology. It measures sales generated from the resource base, not profit retained, and depends on business capital intensity.', 'อัตรากำไร องค์ประกอบสินทรัพย์ และฐานงวดรายได้', 'margins, asset composition and revenue period basis');
explain('inventory_turnover', 'Inventory Turnover', 'อัตราหมุนเวียนสินค้าคงเหลือคือต้นทุนขายเทียบกับสินค้าคงเหลือเฉลี่ยตามฐานที่กำหนด สะท้อนจำนวนรอบที่สินค้าเคลื่อนผ่านกิจการ แต่จำนวนรอบสูงอาจมาพร้อมสินค้าขาดมือและไม่ยืนยันคุณภาพการขายลำพัง.', 'Inventory Turnover compares cost of sales with the accepted average inventory base. It measures inventory cycling, not collection or supplier-payment timing; faster turnover can also accompany inadequate stock availability.', 'รายได้ ต้นทุนขาย อายุสินค้า และความพร้อมส่งมอบ', 'revenue, cost of sales, stock aging and availability');
explain('dio', 'DIO', 'DIO คือระยะเวลาที่สินค้าคงเหลือผูกเงินทุนอยู่ในกิจการโดยประมาณตามต้นทุนขายและฐานสินค้าที่กำหนด สะท้อนจังหวะการผลิตและขาย แต่จำนวนวันเพิ่มไม่ยืนยันปัญหาอุปสงค์หรือสินค้าล้าสมัยโดยไม่มีหลักฐานเพิ่มเติม.', 'DIO estimates how long capital remains tied up in inventory using the accepted cost-of-sales basis. It reflects production and sales timing; a longer duration alone does not prove weak demand or obsolete stock.', 'อายุสินค้า ต้นทุนขาย รายได้ และการหมุนสินค้า', 'inventory aging, cost of sales, revenue and turnover');
explain('dpo', 'DPO', 'DPO คือระยะเวลาชำระเจ้าหนี้การค้าโดยประมาณตามฐานเจ้าหนี้และต้นทุนที่ใช้ในสูตร สะท้อนเครดิตจากผู้ขายและจังหวะเงินจ่าย แต่จำนวนวันที่ยาวขึ้นไม่ยืนยันว่ากิจการมีอำนาจต่อรองหรือขาดสภาพคล่อง.', 'DPO estimates trade-payable payment timing using the accepted payable and cost basis. It reflects supplier credit and cash-payment timing; a longer duration alone establishes neither bargaining power nor liquidity distress.', 'เงื่อนไขคู่ค้า เจ้าหนี้ ต้นทุนขาย และเงินสดดำเนินงาน', 'supplier terms, payables, cost of sales and operating cash flow');
explain('ccc', 'Cash Conversion Cycle', 'วงจรเงินสดใช้ระยะถือสินค้าและเก็บลูกหนี้หักระยะจ่ายเจ้าหนี้ตามวิธีคำนวณที่กำหนด สะท้อนช่วงเวลาที่กิจการต้องสนับสนุนเงินทุนหมุนเวียน โดยตัวเลขรวมอาจซ่อนการเปลี่ยนแปลงคนละทิศทางของแต่ละองค์ประกอบ.', 'Cash Conversion Cycle combines inventory and receivable days less payable days under the accepted methodology. It reflects the timing gap funded by working capital; the aggregate can hide offsetting changes in its components.', 'DSO DIO DPO และกระแสเงินสด', 'DSO, DIO, DPO and operating cash flow');
explain('nim|net_interest_margin_pct', 'Net Interest Margin', 'ส่วนต่างดอกเบี้ยสุทธิคือรายได้ดอกเบี้ยสุทธิเทียบกับสินทรัพย์ก่อรายได้เฉลี่ยตามสูตรและฐานงวดที่กำหนด สะท้อนผลตอบแทนสินทรัพย์หลังต้นทุนแหล่งทุน แต่ไม่ได้รวมความเสียหายเครดิตหรือค่าใช้จ่ายทั้งหมด.', 'Net Interest Margin compares net interest income with average earning assets under the accepted period methodology. It reflects asset yield after funding costs, before the full effects of credit losses and operating expenses.', 'ต้นทุนเงินฝาก สินทรัพย์ก่อรายได้ และคุณภาพเครดิต', 'deposit costs, earning assets and credit quality');
explain('net_interest_income', 'Net Interest Income', 'รายได้ดอกเบี้ยสุทธิคือรายได้ดอกเบี้ยหลังหักค่าใช้จ่ายดอกเบี้ยตามขอบเขตที่รายงาน สะท้อนผลตอบแทนสุทธิจากการรับและปล่อยเงินทุน แต่ไม่ใช่กำไรสุทธิหลังสำรองเครดิตและค่าใช้จ่ายอื่น.', 'Net Interest Income is reported interest income less interest expense. It measures the net funding and lending return, not net profit after credit provisions and other expenses.', 'สินทรัพย์ก่อรายได้ ต้นทุนเงินฝาก NIM และสำรองเครดิต', 'earning assets, deposit costs, NIM and credit provisions');
explain('deposit_growth', 'Deposit Growth', 'การเติบโตของเงินฝากคือการเปลี่ยนยอดเงินฝากบนฐานงวดที่กำหนด สะท้อนการขยายหรือหดตัวของแหล่งทุน แต่ยังต้องดูราคาและความมั่นคงของเงินฝากก่อนสรุปความได้เปรียบหรือสภาพคล่อง.', 'Deposit Growth measures the change in reported deposits on the accepted comparison basis. It reflects expansion or contraction of funding, whose cost and stability must be assessed before inferring advantage or liquidity strength.', 'ต้นทุนเงินฝาก การกระจุกตัว เงินฝากที่ถอนง่าย และสินเชื่อ', 'deposit costs, concentration, withdrawal sensitivity and loans');
explain('deposits', 'Deposits', 'เงินฝากคือภาระต่อผู้ฝากที่สถาบันการเงินรับรู้ ณ วันงบ สะท้อนแหล่งทุนซึ่งอาจมีต้นทุนและกำหนดถอนต่างกัน ไม่ใช่ทุนของผู้ถือหุ้นหรือเงินสดสุทธิที่หักหนี้แล้ว.', 'Deposits measures the obligation to depositors at the balance-sheet date. It reflects funding with differing costs and withdrawal characteristics, not shareholder equity or net cash after debt.', 'ต้นทุนและความมั่นคงของเงินฝาก สภาพคล่อง และสินเชื่อ', 'deposit cost and stability, liquidity and loans');
explain('loan_deposit_ratio', 'Loan to Deposit Ratio', 'อัตราสินเชื่อต่อเงินฝากคือฐานเงินให้กู้เทียบกับเงินฝากตามขอบเขตที่กำหนด สะท้อนเงินฝากที่ถูกนำไปสนับสนุนสินทรัพย์สินเชื่อ แต่ไม่บอกคุณภาพสินเชื่อหรือสภาพคล่องจากแหล่งอื่นทั้งหมด.', 'Loan to Deposit Ratio compares accepted lending balances with deposits. It assesses deposit funding deployed into credit assets, not loan quality or the full liquidity available from other funding sources.', 'สภาพคล่อง แหล่งทุนอื่น คุณภาพสินเชื่อ และข้อจำกัดเงินกองทุน', 'liquidity, alternative funding, credit quality and capital constraints');
explain('loans_held_for_investment', 'Loans Held for Investment', 'สินเชื่อเพื่อถือครองคือยอดเงินให้กู้ที่กิจการถือเพื่อรับผลตอบแทนตามมูลค่าบัญชีที่รายงาน ณ วันงบ สะท้อนสินทรัพย์เครดิตและการใช้แหล่งทุน แต่ยอดมากขึ้นไม่ยืนยันผลตอบแทนหลังความเสี่ยงที่ดีขึ้น.', 'Loans Held for Investment measures the reported carrying amount of lending retained for returns at the balance-sheet date. It reflects credit exposure and funding deployment, not proof of improved risk-adjusted earnings.', 'สำรองเครดิต หนี้เสีย ผลตอบแทนสินเชื่อ และแหล่งทุน', 'credit allowances, problem loans, lending yields and funding');
explain('tier1_capital_ratio', 'Tier One Capital Ratio', 'อัตราเงินกองทุน Tier One คือทุนชั้นที่กำหนดตามผู้กำกับเทียบกับสินทรัพย์เสี่ยง สะท้อนฐานทุนรองรับความเสียหาย โดยขอบเขตทุน Tier One กว้างกว่า CET1 และไม่เท่ากับส่วนผู้ถือหุ้นตามบัญชีเสมอ.', 'Tier One Capital Ratio compares regulatory Tier One capital with risk-weighted assets. It measures loss-absorption capacity; Tier One is broader than CET1 and is not automatically equivalent to accounting equity.', 'องค์ประกอบทุน สินทรัพย์เสี่ยง และข้อกำกับ', 'capital components, risk-weighted assets and applicable regulation');
explain('cet1_ratio', 'CET1 Ratio', 'อัตรา CET1 คือทุนหุ้นสามัญชั้นหลักตามนิยามผู้กำกับเทียบกับสินทรัพย์เสี่ยง สะท้อนฐานทุนคุณภาพหลักที่รองรับความเสียหาย ต้องแยกจาก Tier One และส่วนของผู้ถือหุ้นในงบก่อนเปรียบเทียบ.', 'CET1 Ratio compares regulatory common equity tier-one capital with risk-weighted assets. It assesses core loss-absorbing capital, retaining a scope distinct from broader Tier One and accounting equity.', 'ฐาน CET1 สินทรัพย์เสี่ยง คุณภาพเครดิต และข้อกำกับ', 'CET1 scope, risk-weighted assets, credit quality and applicable regulation');
explain('ffo', 'FFO', 'FFO คือกำไรจากกิจการอสังหาริมทรัพย์ที่ปรับรายการตามนิยาม FFO ที่ยอมรับ เช่น ค่าเสื่อมอสังหาฯ และผลจากการขายทรัพย์สิน สะท้อนผลประกอบการที่ลดผลบัญชีบางชนิด แต่ไม่ใช่กระแสเงินสดหลังรายจ่ายรักษาทรัพย์สิน.', 'FFO adjusts real-estate earnings under the accepted FFO definition, including relevant property depreciation and disposal effects. It supports operating-performance assessment but is not cash remaining after property maintenance expenditure.', 'กระแสเงินสด รายจ่ายรักษาทรัพย์สิน หนี้ และรายการปรับ FFO', 'cash flows, maintenance expenditure, debt and FFO adjustments');
explain('noi', 'NOI', 'NOI คือรายได้ดำเนินงานระดับทรัพย์สินหลังค่าใช้จ่ายดำเนินงานทรัพย์สินตามขอบเขตที่กำหนด สะท้อนเศรษฐศาสตร์ของอสังหาฯ ก่อนภาระระดับกิจการบางชนิด ไม่ใช่กำไรสุทธิของผู้ถือหุ้น.', 'NOI measures property-level operating income after the accepted property expenses. It reflects real-estate operating economics before certain corporate-level burdens, rather than net shareholder earnings.', 'รายได้ค่าเช่า อัตราเช่า ค่าใช้จ่ายทรัพย์สิน และหนี้', 'rental revenue, occupancy, property costs and debt');
explain('rental_revenue', 'Rental Revenue', 'รายได้ค่าเช่าคือรายได้จากการให้ใช้ทรัพย์สินที่รับรู้ในงวด สะท้อนกิจกรรมการเช่าและฐานสัญญา แต่รายได้ที่รับรู้ไม่เท่ากับเงินสดเก็บได้ทั้งหมดและไม่บอกต้นทุนทรัพย์สิน.', 'Rental Revenue measures recognized income from property leasing during the period. It reflects leasing activity and contract scope, not all cash collected or property-level costs.', 'อัตราเช่า เงื่อนไขสัญญา ลูกหนี้ และ NOI', 'occupancy, contract terms, receivables and NOI');
explain('combined_ratio_pct', 'Combined Ratio', 'Combined Ratio รวมต้นทุนสินไหมและค่าใช้จ่ายรับประกันภัยเทียบกับฐานเบี้ยประกันตามสูตรที่กำหนด สะท้อนความสามารถทำกำไรจากการรับประกันก่อนรายได้ลงทุน โดยฐานตัวส่วนและวิธีจัดค่าใช้จ่ายต้องตรงกัน.', 'Combined Ratio compares underwriting losses and expenses with the accepted premium basis. It assesses underwriting profitability before investment income, retaining consistent loss, expense and premium definitions.', 'เบี้ยประกัน สินไหม ค่าใช้จ่าย และการปรับสำรอง', 'premiums, claims, expenses and reserve development');
explain('net_premiums_earned', 'Net Premiums Earned', 'เบี้ยประกันรับรู้สุทธิคือเบี้ยส่วนที่รับรู้เป็นรายได้ตามความคุ้มครองและการประกันต่อในงวด สะท้อนขนาดกิจกรรมรับประกัน ไม่เท่ากับเบี้ยที่เขียนหรือเงินสดรับทั้งหมด.', 'Net Premiums Earned measures premium income recognized for coverage provided, net of the reported reinsurance scope. It reflects underwriting activity, not all written premiums or cash receipts.', 'สินไหม ค่าใช้จ่าย Combined Ratio และการประกันต่อ', 'claims, expenses, combined ratio and reinsurance');
explain('loss_reserve', 'Loss Reserve', 'สำรองสินไหมคือภาระสินไหมที่กิจการรับรู้ ณ วันงบตามการประมาณบัญชี สะท้อนภาระจากความเสี่ยงรับประกันที่ยังต้องชำระ ไม่ใช่สินไหมจ่ายในงวดหรือเงินสดสำรองที่กันไว้ทั้งหมด.', 'Loss Reserve measures the recognized outstanding claims obligation at the balance-sheet date under accounting estimates. It reflects unpaid underwriting liabilities, not period claims paid or a fully segregated cash balance.', 'การพัฒนาสำรอง สินไหมจ่าย การประกันต่อ และเงินกองทุน', 'reserve development, paid claims, reinsurance and capital');

attachBeginnerEducation(METRIC_MEANING_REGISTRY);
export function canonicalMetricMeaning(context: MetricInterpretationContext): { th: string; en: string } {
  return beginnerMeaningForContext(context, METRIC_MEANING_REGISTRY);
}
