import type { BusinessArchetype } from '../../financialMetricContext.js';

export interface CandidateDefinition {
  ticker: string;
  companyName: string;
  archetype: BusinessArchetype;
  sector: string;
  industry: string;
  subIndustry: string;
  revenueModels: string[];
  majorBusinessLines: string[];
  geography: string;
  lifecycle: 'early_stage' | 'growth' | 'mature' | 'cyclical';
  profitabilityState: 'pre_profit' | 'breakeven' | 'profitable';
  capitalIntensity: 'asset_light' | 'moderate' | 'capital_intensive' | 'financial_intermediary';
  regulatoryType?: 'banking' | 'insurance' | 'reit' | 'utility' | 'unregulated' | 'standard';
  scaleTier: 'mega' | 'large' | 'mid' | 'small';
  metrics: Record<string, { value: number | null; unit: string; period: string; source: string; reportedOrDerived: 'REPORTED' | 'DERIVED' }>;
}

/**
 * Deterministic test & offline fixture universe.
 * Invariant: Production discovery must NOT depend on this static universe.
 * Frozen metrics are permitted only in test fixtures.
 */
export const FIXTURE_CANDIDATE_UNIVERSE: CandidateDefinition[] = [
  // 1. FinTech / Digital Banking / Consumer Finance
  {
    ticker: 'SOFI',
    companyName: 'SoFi Technologies, Inc.',
    archetype: 'fintech',
    sector: 'Financial Services',
    industry: 'Credit Services',
    subIndustry: 'digital_banking_lending',
    revenueModels: ['net_interest_income', 'fee_based', 'technology_services'],
    majorBusinessLines: ['lending', 'financial_services', 'technology_platform'],
    geography: 'US',
    lifecycle: 'growth',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'banking',
    scaleTier: 'mid',
    metrics: {
      pe_trailing: { value: 38.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 24.2, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 2.1, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 2.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 34.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 8.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: 1.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 5.85, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 54.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'NU',
    companyName: 'Nu Holdings Ltd.',
    archetype: 'fintech',
    sector: 'Financial Services',
    industry: 'Credit Services',
    subIndustry: 'digital_banking_lending',
    revenueModels: ['net_interest_income', 'fee_based', 'credit_cards'],
    majorBusinessLines: ['digital_banking', 'credit_cards', 'investments'],
    geography: 'LatAm',
    lifecycle: 'growth',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'banking',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 32.4, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 20.8, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 6.2, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 6.5, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 48.6, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 28.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: 3.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 18.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 32.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'AFRM',
    companyName: 'Affirm Holdings, Inc.',
    archetype: 'fintech',
    sector: 'Financial Services',
    industry: 'Credit Services',
    subIndustry: 'bnpl_consumer_finance',
    revenueModels: ['merchant_fees', 'interest_income', 'servicing_fees'],
    majorBusinessLines: ['buy_now_pay_later', 'point_of_sale_financing'],
    geography: 'US',
    lifecycle: 'growth',
    profitabilityState: 'breakeven',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'standard',
    scaleTier: 'mid',
    metrics: {
      pe_trailing: { value: null, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 35.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 4.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 5.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 46.3, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: -8.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: -3.1, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 8.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 68.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'UPST',
    companyName: 'Upstart Holdings, Inc.',
    archetype: 'fintech',
    sector: 'Financial Services',
    industry: 'Credit Services',
    subIndustry: 'ai_lending_marketplace',
    revenueModels: ['referral_fees', 'platform_fees', 'servicing_fees'],
    majorBusinessLines: ['ai_lending_platform', 'loan_origination'],
    geography: 'US',
    lifecycle: 'growth',
    profitabilityState: 'breakeven',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'standard',
    scaleTier: 'mid',
    metrics: {
      pe_trailing: { value: null, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 42.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 3.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 3.7, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 20.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: -12.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: -4.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 6.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 72.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'LC',
    companyName: 'LendingClub Corporation',
    archetype: 'fintech',
    sector: 'Financial Services',
    industry: 'Credit Services',
    subIndustry: 'digital_banking_lending',
    revenueModels: ['net_interest_income', 'marketplace_fees'],
    majorBusinessLines: ['digital_banking', 'personal_loans'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'banking',
    scaleTier: 'small',
    metrics: {
      pe_trailing: { value: 18.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 12.4, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 1.1, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 1.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 14.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 6.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: 0.9, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 6.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 62.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'ALLY',
    companyName: 'Ally Financial Inc.',
    archetype: 'bank',
    sector: 'Financial Services',
    industry: 'Banks—Diversified',
    subIndustry: 'digital_banking_auto_lending',
    revenueModels: ['net_interest_income', 'insurance_premiums', 'fee_based'],
    majorBusinessLines: ['auto_financing', 'digital_deposits', 'commercial_lending'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'banking',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 14.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 9.8, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 0.95, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 1.15, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 6.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 8.9, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: 0.65, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 3.3, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 58.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },

  // 2. Commercial / Depository Banks
  {
    ticker: 'JPM',
    companyName: 'JPMorgan Chase & Co.',
    archetype: 'bank',
    sector: 'Financial Services',
    industry: 'Banks—Diversified',
    subIndustry: 'money_center_bank',
    revenueModels: ['net_interest_income', 'investment_banking', 'asset_management', 'card_services'],
    majorBusinessLines: ['consumer_banking', 'corporate_investment_bank', 'commercial_banking', 'asset_wealth'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'banking',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 12.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 11.5, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 1.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 2.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 11.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 17.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: 1.35, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 2.65, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 52.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'BAC',
    companyName: 'Bank of America Corporation',
    archetype: 'bank',
    sector: 'Financial Services',
    industry: 'Banks—Diversified',
    subIndustry: 'money_center_bank',
    revenueModels: ['net_interest_income', 'wealth_management', 'investment_banking'],
    majorBusinessLines: ['consumer_banking', 'global_wealth', 'global_banking', 'global_markets'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'banking',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 13.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 11.2, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 1.25, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 1.6, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 4.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 10.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: 0.85, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 1.95, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 63.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'WFC',
    companyName: 'Wells Fargo & Company',
    archetype: 'bank',
    sector: 'Financial Services',
    industry: 'Banks—Diversified',
    subIndustry: 'money_center_bank',
    revenueModels: ['net_interest_income', 'mortgage_banking', 'commercial_banking'],
    majorBusinessLines: ['consumer_banking', 'commercial_banking', 'corporate_investment_banking', 'wealth'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'banking',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 12.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 10.5, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 1.35, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      price_to_tbv: { value: 1.65, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 3.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 11.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roa_pct: { value: 0.98, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_interest_margin_pct: { value: 2.75, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      efficiency_ratio_pct: { value: 66.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },

  // 3. Insurance (P&C)
  {
    ticker: 'PGR',
    companyName: 'The Progressive Corporation',
    archetype: 'insurer',
    sector: 'Financial Services',
    industry: 'Insurance—Property & Casualty',
    subIndustry: 'pc_insurance',
    revenueModels: ['net_premiums_earned', 'investment_income'],
    majorBusinessLines: ['personal_auto', 'commercial_auto', 'property'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'insurance',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 16.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 15.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 4.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 19.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 31.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      combined_ratio_pct: { value: 89.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      loss_ratio_pct: { value: 68.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
    },
  },
  {
    ticker: 'TRV',
    companyName: 'The Travelers Companies, Inc.',
    archetype: 'insurer',
    sector: 'Financial Services',
    industry: 'Insurance—Property & Casualty',
    subIndustry: 'pc_insurance',
    revenueModels: ['net_premiums_earned', 'investment_income'],
    majorBusinessLines: ['business_insurance', 'bond_specialty', 'personal_insurance'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'insurance',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 12.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 11.4, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 1.95, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 12.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 16.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      combined_ratio_pct: { value: 94.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      loss_ratio_pct: { value: 72.1, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
    },
  },
  {
    ticker: 'ALL',
    companyName: 'The Allstate Corporation',
    archetype: 'insurer',
    sector: 'Financial Services',
    industry: 'Insurance—Property & Casualty',
    subIndustry: 'pc_insurance',
    revenueModels: ['net_premiums_earned', 'investment_income'],
    majorBusinessLines: ['allstate_protection', 'protection_services'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'financial_intermediary',
    regulatoryType: 'insurance',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 11.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 10.2, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      price_to_book: { value: 2.4, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 10.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      roe_pct: { value: 24.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      combined_ratio_pct: { value: 92.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      loss_ratio_pct: { value: 70.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
    },
  },

  // 4. REIT (Industrial / Logistics)
  {
    ticker: 'PLD',
    companyName: 'Prologis, Inc.',
    archetype: 'reit',
    sector: 'Real Estate',
    industry: 'REIT—Industrial',
    subIndustry: 'industrial_logistics_reit',
    revenueModels: ['rental_income', 'strategic_capital_fees'],
    majorBusinessLines: ['real_estate_operations', 'strategic_capital'],
    geography: 'Global',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'reit',
    scaleTier: 'large',
    metrics: {
      p_ffo_multiple: { value: 21.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      p_affo_multiple: { value: 24.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 11.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      noi_growth_yoy_pct: { value: 7.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      occupancy_rate_pct: { value: 96.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      debt_to_equity: { value: 0.54, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      dividend_yield_pct: { value: 3.2, unit: 'percent', period: 'FY2024', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'REXR',
    companyName: 'Rexford Industrial Realty, Inc.',
    archetype: 'reit',
    sector: 'Real Estate',
    industry: 'REIT—Industrial',
    subIndustry: 'industrial_logistics_reit',
    revenueModels: ['rental_income'],
    majorBusinessLines: ['industrial_properties'],
    geography: 'US',
    lifecycle: 'growth',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'reit',
    scaleTier: 'mid',
    metrics: {
      p_ffo_multiple: { value: 19.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      p_affo_multiple: { value: 22.4, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 16.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      noi_growth_yoy_pct: { value: 8.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      occupancy_rate_pct: { value: 97.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      debt_to_equity: { value: 0.48, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      dividend_yield_pct: { value: 3.6, unit: 'percent', period: 'FY2024', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'FR',
    companyName: 'First Industrial Realty Trust, Inc.',
    archetype: 'reit',
    sector: 'Real Estate',
    industry: 'REIT—Industrial',
    subIndustry: 'industrial_logistics_reit',
    revenueModels: ['rental_income'],
    majorBusinessLines: ['logistics_facilities'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'reit',
    scaleTier: 'mid',
    metrics: {
      p_ffo_multiple: { value: 18.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      p_affo_multiple: { value: 20.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 9.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      noi_growth_yoy_pct: { value: 6.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      occupancy_rate_pct: { value: 95.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      debt_to_equity: { value: 0.62, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      dividend_yield_pct: { value: 3.1, unit: 'percent', period: 'FY2024', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
    },
  },

  // 5. Enterprise Software / SaaS Platform
  {
    ticker: 'MSFT',
    companyName: 'Microsoft Corporation',
    archetype: 'saas_software',
    sector: 'Technology',
    industry: 'Software—Infrastructure',
    subIndustry: 'enterprise_cloud_software',
    revenueModels: ['cloud_subscription', 'software_licenses', 'hardware'],
    majorBusinessLines: ['productivity_business', 'intelligent_cloud', 'more_personal_computing'],
    geography: 'Global',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'moderate',
    regulatoryType: 'unregulated',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 34.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 28.5, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 22.4, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      ev_sales: { value: 12.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 15.7, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 69.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 44.6, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_margin_pct: { value: 36.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 29.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roe_pct: { value: 38.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      fcf_yield_pct: { value: 2.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'ORCL',
    companyName: 'Oracle Corporation',
    archetype: 'saas_software',
    sector: 'Technology',
    industry: 'Software—Infrastructure',
    subIndustry: 'enterprise_cloud_software',
    revenueModels: ['cloud_services', 'license_support', 'hardware'],
    majorBusinessLines: ['cloud_services', 'cloud_license', 'hardware'],
    geography: 'Global',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'moderate',
    regulatoryType: 'unregulated',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 38.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 24.5, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 20.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      ev_sales: { value: 8.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 6.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 71.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 30.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_margin_pct: { value: 19.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 14.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roe_pct: { value: 48.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      fcf_yield_pct: { value: 3.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'CRM',
    companyName: 'Salesforce, Inc.',
    archetype: 'saas_software',
    sector: 'Technology',
    industry: 'Software—Application',
    subIndustry: 'enterprise_cloud_software',
    revenueModels: ['subscription_support', 'professional_services'],
    majorBusinessLines: ['sales_cloud', 'service_cloud', 'platform', 'marketing_cloud'],
    geography: 'Global',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'asset_light',
    regulatoryType: 'unregulated',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 45.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 25.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 21.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      ev_sales: { value: 7.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 11.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 75.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 17.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_margin_pct: { value: 11.9, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 8.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roe_pct: { value: 7.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      fcf_yield_pct: { value: 4.1, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'PLTR',
    companyName: 'Palantir Technologies Inc.',
    archetype: 'saas_software',
    sector: 'Technology',
    industry: 'Software—Infrastructure',
    subIndustry: 'ai_enterprise_platform',
    revenueModels: ['software_subscription', 'professional_services'],
    majorBusinessLines: ['commercial', 'government'],
    geography: 'US',
    lifecycle: 'growth',
    profitabilityState: 'profitable',
    capitalIntensity: 'asset_light',
    regulatoryType: 'unregulated',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 110.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 75.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 68.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      ev_sales: { value: 24.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 24.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 80.6, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 18.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_margin_pct: { value: 15.6, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 12.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roe_pct: { value: 10.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      fcf_yield_pct: { value: 1.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },

  // 6. Energy / Oil & Gas (E&P)
  {
    ticker: 'OXY',
    companyName: 'Occidental Petroleum Corporation',
    archetype: 'energy_commodity',
    sector: 'Energy',
    industry: 'Oil & Gas E&P',
    subIndustry: 'oil_gas_ep',
    revenueModels: ['oil_gas_sales', 'chemical_sales'],
    majorBusinessLines: ['oil_and_gas', 'oxychem', 'midstream_marketing'],
    geography: 'US',
    lifecycle: 'cyclical',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 14.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 12.2, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 5.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: -2.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      operating_margin_pct: { value: 24.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_margin_pct: { value: 15.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 9.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      debt_to_equity: { value: 0.78, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      fcf_yield_pct: { value: 7.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'COP',
    companyName: 'ConocoPhillips',
    archetype: 'energy_commodity',
    sector: 'Energy',
    industry: 'Oil & Gas E&P',
    subIndustry: 'oil_gas_ep',
    revenueModels: ['crude_oil_sales', 'natural_gas_sales'],
    majorBusinessLines: ['exploration_production'],
    geography: 'Global',
    lifecycle: 'cyclical',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 12.4, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 10.8, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 5.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: -1.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      operating_margin_pct: { value: 26.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_margin_pct: { value: 18.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 13.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      debt_to_equity: { value: 0.38, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      fcf_yield_pct: { value: 8.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'EOG',
    companyName: 'EOG Resources, Inc.',
    archetype: 'energy_commodity',
    sector: 'Energy',
    industry: 'Oil & Gas E&P',
    subIndustry: 'oil_gas_ep',
    revenueModels: ['crude_oil_sales', 'natural_gas_sales'],
    majorBusinessLines: ['exploration_production'],
    geography: 'US',
    lifecycle: 'cyclical',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 10.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 9.8, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 4.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 0.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      operating_margin_pct: { value: 32.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      net_margin_pct: { value: 23.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 16.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      debt_to_equity: { value: 0.15, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      fcf_yield_pct: { value: 8.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },

  // 7. Early-Stage / Pre-Profit Space & Tech
  {
    ticker: 'RKLB',
    companyName: 'Rocket Lab USA, Inc.',
    archetype: 'early_stage',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    subIndustry: 'space_launch_systems',
    revenueModels: ['launch_contracts', 'space_systems_sales'],
    majorBusinessLines: ['launch_services', 'space_systems'],
    geography: 'US',
    lifecycle: 'early_stage',
    profitabilityState: 'pre_profit',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'mid',
    metrics: {
      ev_sales: { value: 14.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 42.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 27.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      cash_runway_months: { value: 28, unit: 'count', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'ASTS',
    companyName: 'AST SpaceMobile, Inc.',
    archetype: 'early_stage',
    sector: 'Technology',
    industry: 'Telecommunications',
    subIndustry: 'satellite_broadband',
    revenueModels: ['gateway_services', 'commercial_agreements'],
    majorBusinessLines: ['space_cellular_network'],
    geography: 'US',
    lifecycle: 'early_stage',
    profitabilityState: 'pre_profit',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'mid',
    metrics: {
      ev_sales: { value: 28.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 120.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: -15.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      cash_runway_months: { value: 18, unit: 'count', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'LUNR',
    companyName: 'Intuitive Machines, Inc.',
    archetype: 'early_stage',
    sector: 'Industrials',
    industry: 'Aerospace & Defense',
    subIndustry: 'lunar_services',
    revenueModels: ['nasa_contracts', 'commercial_payloads'],
    majorBusinessLines: ['lunar_access', 'orbital_services'],
    geography: 'US',
    lifecycle: 'early_stage',
    profitabilityState: 'pre_profit',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'small',
    metrics: {
      ev_sales: { value: 6.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 85.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 12.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      cash_runway_months: { value: 16, unit: 'count', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },

  // 8. Semiconductor (Fabless vs Foundry vs Equipment)
  {
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    archetype: 'semiconductor',
    sector: 'Technology',
    industry: 'Semiconductors',
    subIndustry: 'fabless_accelerator',
    revenueModels: ['compute_networking_sales', 'graphics_sales'],
    majorBusinessLines: ['data_center', 'gaming', 'professional_visualization', 'auto'],
    geography: 'Global',
    lifecycle: 'growth',
    profitabilityState: 'profitable',
    capitalIntensity: 'asset_light',
    regulatoryType: 'unregulated',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 42.5, unit: 'x', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 30.0, unit: 'x', period: 'FY2026E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 32.0, unit: 'x', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      ev_sales: { value: 18.0, unit: 'x', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 114.0, unit: 'percent', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 75.0, unit: 'percent', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 62.0, unit: 'percent', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 68.0, unit: 'percent', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'AMD',
    companyName: 'Advanced Micro Devices, Inc.',
    archetype: 'semiconductor',
    sector: 'Technology',
    industry: 'Semiconductors',
    subIndustry: 'fabless_accelerator',
    revenueModels: ['data_center_sales', 'client_sales', 'gaming_sales'],
    majorBusinessLines: ['data_center', 'client', 'gaming', 'embedded'],
    geography: 'Global',
    lifecycle: 'growth',
    profitabilityState: 'profitable',
    capitalIntensity: 'asset_light',
    regulatoryType: 'unregulated',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 45.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 26.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 24.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      ev_sales: { value: 7.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 14.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 50.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 11.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 14.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'TSM',
    companyName: 'Taiwan Semiconductor Manufacturing Company Limited',
    archetype: 'semiconductor',
    sector: 'Technology',
    industry: 'Semiconductors',
    subIndustry: 'foundry_manufacturing',
    revenueModels: ['wafer_manufacturing_fees'],
    majorBusinessLines: ['advanced_nodes', 'specialty_nodes'],
    geography: 'Global',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'unregulated',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 24.5, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 18.5, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 12.0, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      ev_sales: { value: 8.5, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 29.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 54.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 43.1, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 28.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'ASML',
    companyName: 'ASML Holding N.V.',
    archetype: 'semiconductor',
    sector: 'Technology',
    industry: 'Semiconductor Equipment',
    subIndustry: 'lithography_equipment',
    revenueModels: ['equipment_sales', 'service_field_options'],
    majorBusinessLines: ['euv_systems', 'duv_systems', 'metrology_inspection'],
    geography: 'Global',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'moderate',
    regulatoryType: 'unregulated',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 38.0, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 25.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 26.0, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      ev_sales: { value: 10.2, unit: 'x', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 12.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 51.3, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 31.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 38.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 20-F', reportedOrDerived: 'DERIVED' },
    },
  },

  // 9. Retail: Physical / Omnichannel vs Digital Marketplace
  {
    ticker: 'WMT',
    companyName: 'Walmart Inc.',
    archetype: 'retail',
    sector: 'Consumer Defensive',
    industry: 'Discount Stores',
    subIndustry: 'physical_omnichannel_retail',
    revenueModels: ['merchandise_sales', 'membership_fees'],
    majorBusinessLines: ['walmart_us', 'walmart_international', 'sams_club'],
    geography: 'Global',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 32.0, unit: 'x', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 26.5, unit: 'x', period: 'FY2026E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 16.5, unit: 'x', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 5.5, unit: 'percent', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 24.5, unit: 'percent', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 4.2, unit: 'percent', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 14.5, unit: 'percent', period: 'FY2025', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'TGT',
    companyName: 'Target Corporation',
    archetype: 'retail',
    sector: 'Consumer Defensive',
    industry: 'Discount Stores',
    subIndustry: 'physical_omnichannel_retail',
    revenueModels: ['merchandise_sales'],
    majorBusinessLines: ['stores_digital'],
    geography: 'US',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 14.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 13.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 8.8, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 1.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 27.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 5.3, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 15.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'AMZN',
    companyName: 'Amazon.com, Inc.',
    archetype: 'digital_marketplace',
    sector: 'Consumer Cyclical',
    industry: 'Internet Retail',
    subIndustry: 'digital_marketplace_cloud',
    revenueModels: ['online_stores', 'third_party_seller_services', 'aws_cloud', 'advertising'],
    majorBusinessLines: ['north_america', 'international', 'aws'],
    geography: 'Global',
    lifecycle: 'growth',
    profitabilityState: 'profitable',
    capitalIntensity: 'capital_intensive',
    regulatoryType: 'standard',
    scaleTier: 'mega',
    metrics: {
      pe_trailing: { value: 40.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 28.0, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 18.0, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 11.8, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 48.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 9.2, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 16.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
  {
    ticker: 'EBAY',
    companyName: 'eBay Inc.',
    archetype: 'digital_marketplace',
    sector: 'Consumer Cyclical',
    industry: 'Internet Retail',
    subIndustry: 'digital_marketplace_cloud',
    revenueModels: ['take_rate_commission', 'advertising'],
    majorBusinessLines: ['marketplace_platform'],
    geography: 'Global',
    lifecycle: 'mature',
    profitabilityState: 'profitable',
    capitalIntensity: 'asset_light',
    regulatoryType: 'standard',
    scaleTier: 'large',
    metrics: {
      pe_trailing: { value: 15.2, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      pe_forward: { value: 12.8, unit: 'x', period: 'FY2025E', source: 'Consensus Snapshot', reportedOrDerived: 'DERIVED' },
      ev_ebitda: { value: 10.5, unit: 'x', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      revenue_growth_yoy_pct: { value: 4.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'REPORTED' },
      gross_margin_pct: { value: 71.5, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      operating_margin_pct: { value: 22.4, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
      roic_pct: { value: 18.0, unit: 'percent', period: 'FY2024', source: 'SEC Form 10-K', reportedOrDerived: 'DERIVED' },
    },
  },
];

export const PUBLIC_CANDIDATE_UNIVERSE = FIXTURE_CANDIDATE_UNIVERSE;
