import type { FinancialStatementsData, ReportData } from '../types';
import type { CanonicalFinancialDataset } from '../domain/financialValue';
import type { SecShareSnapshot } from '../services/sec/secShareSnapshot';

import type { SecPeriodStatement } from '../domain/secVerification';

export type { SecPeriodStatement };

export interface SecFilingPeriodDiff {
  ticker?: string;
  currentPeriod: string;
  priorPeriod: string;
  comparisonType: 'annual_yoy' | 'quarter_yoy';
  currentFiling?: {
    form?: string | null;
    accession?: string | null;
    filed_date?: string | null;
    period_end?: string | null;
    units?: string | null;
    fiscal_year?: number | null;
    fiscal_quarter?: number | null;
  };
  priorFiling?: {
    form?: string | null;
    accession?: string | null;
    filed_date?: string | null;
    period_end?: string | null;
    units?: string | null;
    fiscal_year?: number | null;
    fiscal_quarter?: number | null;
  };
  revenueYoYPct: number | null;
  operatingIncomeYoYPct: number | null;
  netIncomeYoYPct: number | null;
  ocfYoYPct: number | null;
  fcfYoYPct: number | null;
  operatingMarginCurrentPct: number | null;
  operatingMarginPriorPct: number | null;
  operatingMarginBpsDelta: number | null;
  shareCountDeltaPct: number | null;
  dilutionOrBuyback: 'buybacks' | 'dilution' | 'stable' | 'unavailable';
  ocfToNetIncomeRatioCurrent: number | null;
  ocfToNetIncomeRatioPrior: number | null;
  cashConversionStatus: 'healthy' | 'warning' | 'neutral' | 'unavailable';
  cashConversionSummary: string;
  workingCapitalNote?: string;
}

function parseNum(val: any): number | null {
  if (typeof val === 'number' && Number.isFinite(val)) return val;
  if (typeof val === 'string') {
    const p = parseFloat(val.replace(/[^0-9.-]/g, ''));
    if (Number.isFinite(p)) return p;
  }
  return null;
}

/**
 * Adapts FinancialStatementsData, CanonicalFinancialDataset, or ReportData into typed SecPeriodStatement[]
 * for period-over-period diffing and SEC filing audit.
 * Replaces synthetic or legacy shapes with Lumina's canonical model.
 *
 * Strict Financial Integrity Invariant:
 * AI-generated report.financial_statements must NEVER be treated as canonical SEC facts,
 * even if sec_verification.status === 'verified_eligible'.
 * Only verified CanonicalFinancialDataset or verified sec_period_statements may be adapted.
 */
export function adaptFinancialStatementsToSecPeriodStatements(
  input?: FinancialStatementsData | CanonicalFinancialDataset | ReportData | null,
  shareSnapshot?: SecShareSnapshot | null
): SecPeriodStatement[] {
  if (!input) return [];

  // Case 1: ReportData wrapper
  if ('ticker' in input && ('canonical_financials' in input || 'financial_statements' in input || 'sec_verification' in input)) {
    const report = input as ReportData;

    // FIRST prefer verified SEC period statements from SEC verification endpoint / canonical mapper
    const secStatements = report.sec_verification?.sec_period_statements;
    if (Array.isArray(secStatements) && secStatements.length > 0) {
      return secStatements;
    }

    // Only use report.canonical_financials when the dataset independently proves verified SEC authority:
    // 1. provenanceStatus === 'verified'
    // 2. generatedBy contains 'sec-xbrl'
    const canonical = report.canonical_financials;
    if (
      canonical &&
      canonical.provenanceStatus === 'verified' &&
      typeof canonical.generatedBy === 'string' &&
      /sec-xbrl/i.test(canonical.generatedBy)
    ) {
      return adaptFinancialStatementsToSecPeriodStatements(canonical, shareSnapshot);
    }

    // Never adapt unverified report-derived canonical_financials or AI report.financial_statements into SEC Period Statements
    return [];
  }

  // Case 2: CanonicalFinancialDataset
  if ('schemaVersion' in input && 'values' in input && Array.isArray(input.periods)) {
    const dataset = input as CanonicalFinancialDataset;

    // Strict SEC Authority Invariant:
    // Raw CanonicalFinancialDataset must independently prove verified SEC authority.
    // Datasets generated by 'lumina-financial-provenance-v1' (from report.financial_statements)
    // or with unverified / source_linked provenance must NEVER be promoted to SEC verified statements.
    if (
      dataset.provenanceStatus !== 'verified' ||
      typeof dataset.generatedBy !== 'string' ||
      !/sec-xbrl/i.test(dataset.generatedBy)
    ) {
      return [];
    }

    if (dataset.periods.length === 0) return [];

    const getValWithSource = (metricKey: string, period: string, index: number) => {
      const series = dataset.values[metricKey];
      if (!Array.isArray(series)) return { val: null, source: undefined, unit: undefined };
      const item = series.find((v) => v.period === period) ?? series[index];
      const val = (item && typeof item.value === 'number' && Number.isFinite(item.value)) ? item.value : null;
      return { val, source: item?.source, unit: item?.unit };
    };

    return dataset.periods.map((period, i) => {
      const isLatest = i === dataset.periods.length - 1;
      const revInfo = getValWithSource('income_statement.revenue', period, i);
      const opIncInfo = getValWithSource('income_statement.operating_income', period, i);
      const interestExpenseInfo = getValWithSource('income_statement.interest_expense', period, i);
      const netIncInfo = getValWithSource('income_statement.net_income', period, i);
      const ocfInfo = getValWithSource('cash_flow.operating_cash_flow', period, i);
      const capexInfo = getValWithSource('cash_flow.capex', period, i);
      const debtInfo = getValWithSource('balance_sheet.total_debt', period, i);
      const equityInfo = getValWithSource('balance_sheet.total_equity', period, i);
      const arInfo = getValWithSource('balance_sheet.accounts_receivable', period, i);
      const invInfo = getValWithSource('balance_sheet.inventory', period, i);
      const apInfo = getValWithSource('balance_sheet.accounts_payable', period, i);

      const primarySource = revInfo.source || netIncInfo.source || opIncInfo.source || ocfInfo.source;
      const primaryUnit = revInfo.unit || netIncInfo.unit || opIncInfo.unit || ocfInfo.unit || 'USD_M';

      return {
        ticker: dataset.ticker,
        period,
        form: (primarySource as any)?.form || primarySource?.documentType || null,
        accession: (primarySource as any)?.accession || primarySource?.accessionNumber || null,
        filed_date: (primarySource as any)?.filed || primarySource?.filingDate || null,
        period_end: primarySource?.periodEnd || null,
        units: (primarySource as any)?.unit || primaryUnit || 'USD',
        revenue: revInfo.val,
        operating_income: opIncInfo.val,
        interest_expense: interestExpenseInfo.val,
        net_income: netIncInfo.val,
        operating_cash_flow: ocfInfo.val,
        capital_expenditure: capexInfo.val,
        total_debt: debtInfo.val,
        stockholders_equity: equityInfo.val,
        accounts_receivable: arInfo.val,
        inventory: invInfo.val,
        accounts_payable: apInfo.val,
        diluted_shares: isLatest
          ? (shareSnapshot?.latestDilutedWeightedAverageShares?.sharesM ?? null)
          : null,
      };
    });
  }

  // Case 3: Raw FinancialStatementsData without verified SEC provenance
  // Strict Financial Integrity Invariant:
  // Raw AI report.financial_statements has no canonical SEC provenance and must NEVER be adapted as verified SEC statements.
  return [];
}

export interface ParsedPeriodDescriptor {
  statement: SecPeriodStatement;
  isAnnual: boolean;
  isQuarterly: boolean;
  fiscalYear: number;
  quarter: 1 | 2 | 3 | 4 | null;
  sortKey: number;
}

/**
 * Parses and normalizes a period descriptor from statement string or fiscal_year.
 */
export function parsePeriodDescriptor(statement: SecPeriodStatement): ParsedPeriodDescriptor | null {
  const raw = String(statement.period || '').trim();

  // 1. Check Quarterly: e.g. "Q3 2025", "Q1 FY24", "Q4 2023"
  const qMatch = raw.match(/^Q([1-4])\s*(?:FY\s*)?(\d{2,4})$/i);
  if (qMatch) {
    const q = parseInt(qMatch[1], 10) as 1 | 2 | 3 | 4;
    let yr = parseInt(qMatch[2], 10);
    if (yr < 100) yr += 2000;
    return {
      statement,
      isAnnual: false,
      isQuarterly: true,
      fiscalYear: yr,
      quarter: q,
      sortKey: yr * 10 + q,
    };
  }

  // 1b. Check Quarterly reverse/delimited format: e.g. "2025-Q3", "2025 Q3", "2025/Q3", "FY2025-Q3"
  const qMatchRev = raw.match(/^(?:FY\s*)?(\d{2,4})[-/\s]+Q([1-4])$/i);
  if (qMatchRev) {
    let yr = parseInt(qMatchRev[1], 10);
    if (yr < 100) yr += 2000;
    const q = parseInt(qMatchRev[2], 10) as 1 | 2 | 3 | 4;
    return {
      statement,
      isAnnual: false,
      isQuarterly: true,
      fiscalYear: yr,
      quarter: q,
      sortKey: yr * 10 + q,
    };
  }

  // 1c. Check Quarter-only if explicit fiscal_year is provided: e.g. "Q3" with fiscal_year: 2025
  const qOnlyMatch = raw.match(/^Q([1-4])$/i);
  if (qOnlyMatch && typeof statement.fiscal_year === 'number' && statement.fiscal_year > 1900) {
    const q = parseInt(qOnlyMatch[1], 10) as 1 | 2 | 3 | 4;
    return {
      statement,
      isAnnual: false,
      isQuarterly: true,
      fiscalYear: statement.fiscal_year,
      quarter: q,
      sortKey: statement.fiscal_year * 10 + q,
    };
  }

  // 2. Check Annual: e.g. "FY2025", "FY 2025", "FY25", "2024"
  const aMatch = raw.match(/^(?:FY\s*)?(\d{2,4})$/i);
  if (aMatch) {
    let yr = parseInt(aMatch[1], 10);
    if (yr < 100) yr += 2000;
    return {
      statement,
      isAnnual: true,
      isQuarterly: false,
      fiscalYear: yr,
      quarter: null,
      sortKey: yr * 10,
    };
  }

  // 3. Fallback: statement.fiscal_year if explicit
  if (typeof statement.fiscal_year === 'number' && statement.fiscal_year > 1900) {
    return {
      statement,
      isAnnual: true,
      isQuarterly: false,
      fiscalYear: statement.fiscal_year,
      quarter: null,
      sortKey: statement.fiscal_year * 10,
    };
  }

  return null;
}

/**
 * Resolves the prior-year comparable SEC statement for a target statement.
 * - For quarterly: strictly same quarter, prior fiscal year (target.fiscalYear - 1, target.quarter === prior.quarter).
 * - For annual: strictly prior fiscal year (target.fiscalYear - 1).
 * Never returns QoQ (e.g. Q4 vs Q3) or non-consecutive years.
 * Shuffled statement order produces the exact same deterministic result.
 */
export function findComparablePriorSecStatement(
  statements: SecPeriodStatement[],
  targetStatement?: SecPeriodStatement
): SecPeriodStatement | null {
  if (!Array.isArray(statements) || statements.length === 0) return null;

  const parsedDescriptors: ParsedPeriodDescriptor[] = [];
  for (const s of statements) {
    const desc = parsePeriodDescriptor(s);
    if (desc) parsedDescriptors.push(desc);
  }

  if (parsedDescriptors.length === 0) return null;

  let targetDesc: ParsedPeriodDescriptor | null = null;
  if (targetStatement) {
    targetDesc = parsePeriodDescriptor(targetStatement);
  }

  if (!targetDesc) {
    // If no target provided, sort descending by sortKey and pick the latest
    parsedDescriptors.sort((a, b) => b.sortKey - a.sortKey);
    targetDesc = parsedDescriptors[0];
  }

  if (targetDesc.isAnnual) {
    // Look strictly for fiscalYear - 1 annual statement
    const matched = parsedDescriptors.find(
      (d) => d.isAnnual && d.fiscalYear === targetDesc!.fiscalYear - 1
    );
    return matched ? matched.statement : null;
  }

  if (targetDesc.isQuarterly) {
    // Look strictly for same quarter in fiscalYear - 1
    const matched = parsedDescriptors.find(
      (d) => d.isQuarterly && d.quarter === targetDesc!.quarter && d.fiscalYear === targetDesc!.fiscalYear - 1
    );
    return matched ? matched.statement : null;
  }

  return null;
}

/**
 * Pure deterministic period-over-period diffing for SEC verified financial statements.
 * Strict financial invariants:
 * 1. Comparable Period Matching (P1-1):
 *    - Only compares Annual vs Annual (e.g. FY2025 vs FY2024) or Same-Quarter YoY (e.g. Q3 2025 vs Q3 2024).
 *    - Rejects mixing a quarterly period with an annual period.
 *    - Enforces chronological ordering (newer vs older) regardless of array input order.
 * 2. Fact-Grounded Cash Conversion Analysis (P1-2):
 *    - Evaluates factual OCF-to-Net Income ratio and working capital deltas without speculative qualitative guessing.
 */
export function diffSecFinancialStatements(
  statements: SecPeriodStatement[],
  isThai = false
): SecFilingPeriodDiff | null {
  if (!Array.isArray(statements) || statements.length < 2) {
    return null;
  }

  // 1. Parse and validate period descriptors
  const parsedDescriptors: ParsedPeriodDescriptor[] = [];
  for (const s of statements) {
    const desc = parsePeriodDescriptor(s);
    if (desc) parsedDescriptors.push(desc);
  }

  if (parsedDescriptors.length < 2) {
    return null;
  }

  // 2. Match comparable period pairs
  let curDesc: ParsedPeriodDescriptor | null = null;
  let priorDesc: ParsedPeriodDescriptor | null = null;
  let comparisonType: 'annual_yoy' | 'quarter_yoy' = 'annual_yoy';

  // Strategy A: Annual vs Annual comparison
  const annuals = parsedDescriptors
    .filter((d) => d.isAnnual)
    .sort((a, b) => b.sortKey - a.sortKey);

  if (annuals.length >= 2) {
    curDesc = annuals[0];
    // Find the immediately preceding annual period (strictly fiscalYear - 1)
    const matchedPrior = annuals.find((d) => d.fiscalYear === curDesc!.fiscalYear - 1);
    if (matchedPrior) {
      priorDesc = matchedPrior;
      comparisonType = 'annual_yoy';
    }
  }

  // Strategy B: Same-Quarter YoY comparison (e.g. Q3 2025 vs Q3 2024)
  if (!curDesc || !priorDesc) {
    const quarterlies = parsedDescriptors
      .filter((d) => d.isQuarterly)
      .sort((a, b) => b.sortKey - a.sortKey);

    if (quarterlies.length >= 2) {
      const candidateCur = quarterlies[0];
      // Find matching prior year quarter (strictly same quarter, immediately preceding fiscalYear - 1)
      const matchedPriorQuarter = quarterlies.find(
        (d) => d.quarter === candidateCur.quarter && d.fiscalYear === candidateCur.fiscalYear - 1
      );

      if (matchedPriorQuarter) {
        curDesc = candidateCur;
        priorDesc = matchedPriorQuarter;
        comparisonType = 'quarter_yoy';
      }
    }
  }

  // If no comparable period pair can be verified, fail closed
  if (!curDesc || !priorDesc) {
    return null;
  }

  const cur = curDesc.statement;
  const prior = priorDesc.statement;

  const curRev = parseNum(cur.revenue);
  const priorRev = parseNum(prior.revenue);

  const curOpInc = parseNum(cur.operating_income);
  const priorOpInc = parseNum(prior.operating_income);

  const curNetInc = parseNum(cur.net_income);
  const priorNetInc = parseNum(prior.net_income);

  const curOcf = parseNum(cur.operating_cash_flow);
  const priorOcf = parseNum(prior.operating_cash_flow);

  const curCapex = parseNum(cur.capital_expenditure);
  const priorCapex = parseNum(prior.capital_expenditure);

  const curShares = parseNum(cur.diluted_shares);
  const priorShares = parseNum(prior.diluted_shares);

  // YoY Calculations with zero-division protection
  const revenueYoYPct = (curRev !== null && priorRev !== null && priorRev !== 0)
    ? Number((((curRev - priorRev) / Math.abs(priorRev)) * 100).toFixed(2))
    : null;

  const operatingIncomeYoYPct = (curOpInc !== null && priorOpInc !== null && priorOpInc !== 0)
    ? Number((((curOpInc - priorOpInc) / Math.abs(priorOpInc)) * 100).toFixed(2))
    : null;

  const netIncomeYoYPct = (curNetInc !== null && priorNetInc !== null && priorNetInc !== 0)
    ? Number((((curNetInc - priorNetInc) / Math.abs(priorNetInc)) * 100).toFixed(2))
    : null;

  const ocfYoYPct = (curOcf !== null && priorOcf !== null && priorOcf !== 0)
    ? Number((((curOcf - priorOcf) / Math.abs(priorOcf)) * 100).toFixed(2))
    : null;

  // FCF = OCF - |CapEx|
  let curFcf: number | null = null;
  if (curOcf !== null && curCapex !== null) {
    curFcf = curOcf - Math.abs(curCapex);
  }
  let priorFcf: number | null = null;
  if (priorOcf !== null && priorCapex !== null) {
    priorFcf = priorOcf - Math.abs(priorCapex);
  }
  const fcfYoYPct = (curFcf !== null && priorFcf !== null && priorFcf !== 0)
    ? Number((((curFcf - priorFcf) / Math.abs(priorFcf)) * 100).toFixed(2))
    : null;

  // Operating Margins
  const curOpMargin = (curOpInc !== null && curRev !== null && curRev > 0)
    ? (curOpInc / curRev) * 100
    : null;
  const priorOpMargin = (priorOpInc !== null && priorRev !== null && priorRev > 0)
    ? (priorOpInc / priorRev) * 100
    : null;

  const operatingMarginBpsDelta = (curOpMargin !== null && priorOpMargin !== null)
    ? Number(((curOpMargin - priorOpMargin) * 100).toFixed(0))
    : null;

  // Shares & Dilution Pace
  let shareCountDeltaPct: number | null = null;
  let dilutionOrBuyback: 'buybacks' | 'dilution' | 'stable' | 'unavailable' = 'unavailable';
  if (curShares !== null && priorShares !== null && priorShares > 0) {
    shareCountDeltaPct = Number((((curShares - priorShares) / priorShares) * 100).toFixed(2));
    if (shareCountDeltaPct < -0.1) dilutionOrBuyback = 'buybacks';
    else if (shareCountDeltaPct > 0.1) dilutionOrBuyback = 'dilution';
    else dilutionOrBuyback = 'stable';
  }

  // Cash Conversion Quality (P1-2):
  // Grounded in factual OCF-to-Net Income ratio
  const ocfToNetIncomeRatioCurrent = (curNetInc !== null && curNetInc !== 0 && curOcf !== null)
    ? Number((curOcf / curNetInc).toFixed(2))
    : null;

  const ocfToNetIncomeRatioPrior = (priorNetInc !== null && priorNetInc !== 0 && priorOcf !== null)
    ? Number((priorOcf / priorNetInc).toFixed(2))
    : null;

  // Factual working capital check (Accounts Receivable YoY vs Revenue YoY)
  const curAr = parseNum(cur.accounts_receivable);
  const priorAr = parseNum(prior.accounts_receivable);
  let workingCapitalNote: string | undefined;

  if (curAr !== null && priorAr !== null && priorAr > 0 && revenueYoYPct !== null) {
    const arDeltaPct = Number((((curAr - priorAr) / priorAr) * 100).toFixed(1));
    if (arDeltaPct > revenueYoYPct + 10) {
      workingCapitalNote = isThai
        ? `ลูกหนี้การค้าขยายตัว (+${arDeltaPct}%) เร็วกว่าอัตราการเติบโตของรายได้ (+${revenueYoYPct.toFixed(1)}%)`
        : `Accounts receivable expanded (+${arDeltaPct}%) faster than revenue growth (+${revenueYoYPct.toFixed(1)}%).`;
    }
  }

  // Fact-based Cash Conversion Status
  let cashConversionStatus: 'healthy' | 'warning' | 'neutral' | 'unavailable' = 'unavailable';
  let cashConversionSummary: string;

  if (curNetInc === null || curOcf === null) {
    // Missing inputs cannot prove healthy cash conversion
    cashConversionStatus = 'unavailable';
    cashConversionSummary = isThai
      ? 'ไม่มีข้อมูลการแปลงเงินสด — ข้อมูล OCF หรือกำไรสุทธิไม่เพียงพอสำหรับการเปรียบเทียบ'
      : 'Cash conversion unavailable — insufficient comparable OCF / Net Income data.';
  } else if (curNetInc > 0 && curOcf < 0) {
    // Severe divergence: profitable on accrual basis, burning cash on operations
    cashConversionStatus = 'warning';
    cashConversionSummary = isThai
      ? `ระวัง: กำไรสุทธิเป็นบวก ($${curNetInc.toLocaleString()}M) แต่กระแสเงินสดจากการดำเนินงานกลับติดลบ ($${curOcf.toLocaleString()}M)`
      : `Divergence Alert: Positive net income ($${curNetInc.toLocaleString()}M) accompanied by negative operating cash flow ($${curOcf.toLocaleString()}M).`;
  } else if (revenueYoYPct !== null && ocfYoYPct !== null && revenueYoYPct > 0 && ocfYoYPct < 0) {
    // Topline expansion with cash contraction
    cashConversionStatus = 'warning';
    cashConversionSummary = isThai
      ? `ความต่างของกระแสเงินสด: รายได้ขยายตัว (+${revenueYoYPct.toFixed(1)}%) แต่ OCF ลดลง (${ocfYoYPct.toFixed(1)}%) อัตราส่วน OCF/NI อยู่ที่ ${ocfToNetIncomeRatioCurrent !== null ? ocfToNetIncomeRatioCurrent + 'x' : 'N/A'}`
      : `Cash conversion divergence: Revenue grew (+${revenueYoYPct.toFixed(1)}%) while Operating Cash Flow contracted (${ocfYoYPct.toFixed(1)}%). Current OCF/NI: ${ocfToNetIncomeRatioCurrent !== null ? ocfToNetIncomeRatioCurrent + 'x' : 'N/A'}.`;
  } else if (ocfToNetIncomeRatioCurrent !== null && ocfToNetIncomeRatioCurrent >= 1.0) {
    // High earnings quality: OCF fully covers Net Income
    cashConversionStatus = 'healthy';
    cashConversionSummary = isThai
      ? `คุณภาพกระแสเงินสดแข็งแกร่ง: อัตราส่วน OCF ต่อกำไรสุทธิอยู่ที่ ${ocfToNetIncomeRatioCurrent}x (กำไรได้รับการสนับสนุนด้วยเงินสดจริงเต็มจำนวน)`
      : `High earnings quality: OCF-to-Net Income ratio of ${ocfToNetIncomeRatioCurrent}x confirms robust cash-backed accounting profits.`;
  } else if (ocfToNetIncomeRatioCurrent !== null && ocfToNetIncomeRatioCurrent < 0.70 && curNetInc > 0) {
    // Below benchmark conversion
    cashConversionStatus = 'warning';
    cashConversionSummary = isThai
      ? `อัตราการแปลงกำไรเป็นเงินสดต่ำ: OCF คิดเป็นเพียง ${ocfToNetIncomeRatioCurrent}x ของกำไรสุทธิ (ต่ำกว่าเกณฑ์สถาบัน 1.0x)`
      : `Subdued cash conversion: OCF is ${ocfToNetIncomeRatioCurrent}x of net income (below the 1.0x institutional benchmark).`;
  } else if (ocfToNetIncomeRatioCurrent !== null) {
    cashConversionStatus = 'neutral';
    cashConversionSummary = isThai
      ? `กระแสเงินสดจากการดำเนินงานสอดคล้องกับผลการดำเนินงาน (อัตราส่วน OCF/NI: ${ocfToNetIncomeRatioCurrent}x)`
      : `Operating cash flow aligns with reported earnings (OCF/NI: ${ocfToNetIncomeRatioCurrent}x).`;
  } else {
    cashConversionStatus = 'unavailable';
    cashConversionSummary = isThai
      ? 'ไม่มีข้อมูลการแปลงเงินสด — ข้อมูล OCF หรือกำไรสุทธิไม่เพียงพอสำหรับการเปรียบเทียบ'
      : 'Cash conversion unavailable — insufficient comparable OCF / Net Income data.';
  }

  return {
    ticker: cur.ticker || prior.ticker,
    currentPeriod: cur.period,
    priorPeriod: prior.period,
    comparisonType,
    currentFiling: {
      form: cur.form,
      accession: cur.accession,
      filed_date: cur.filed_date,
      period_end: cur.period_end,
      units: cur.units,
      fiscal_year: curDesc.fiscalYear,
      fiscal_quarter: curDesc.quarter,
    },
    priorFiling: {
      form: prior.form,
      accession: prior.accession,
      filed_date: prior.filed_date,
      period_end: prior.period_end,
      units: prior.units,
      fiscal_year: priorDesc.fiscalYear,
      fiscal_quarter: priorDesc.quarter,
    },
    revenueYoYPct,
    operatingIncomeYoYPct,
    netIncomeYoYPct,
    ocfYoYPct,
    fcfYoYPct,
    operatingMarginCurrentPct: curOpMargin !== null ? Number(curOpMargin.toFixed(1)) : null,
    operatingMarginPriorPct: priorOpMargin !== null ? Number(priorOpMargin.toFixed(1)) : null,
    operatingMarginBpsDelta,
    shareCountDeltaPct,
    dilutionOrBuyback,
    ocfToNetIncomeRatioCurrent,
    ocfToNetIncomeRatioPrior,
    cashConversionStatus,
    cashConversionSummary,
    workingCapitalNote,
  };
}
